@startuml
!include ../../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAcademyDirectory <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AcademyDirectory
Class ReadOnlyAcademyDirectory
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueStudentList
Class Student
Class StudioRecord
Class Email
Class Telegram
Class Name
Class Phone
Class Tag
Class Assessment

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AcademyDirectory .up.|> ReadOnlyAcademyDirectory

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAcademyDirectory
ModelManager -left-> "1" AcademyDirectory
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AcademyDirectory *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Name
Student *--> Phone
Student *--> Email
Student *--> Telegram
Student *--> StudioRecord
Student *--> Assessment
Student *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> StudioRecord
StudioRecord -[hidden]right-> Email
Email -[hidden]right-> Telegram

ModelManager -->"~* filtered" Student
@enduml
