package seedu.address.logic.commands;

public enum CommandType {
    FRIEND_ADD, FRIEND_EDIT, FRIEND_ADD_GAME_SKILL, FRIEND_DELETE, FRIEND_GET, FRIEND_LIST, FRIEND_SCHEDULE,
    FRIEND_LINK, FRIEND_UNLINK,
    GAME_ADD, GAME_DELETE, GAME_GET, GAME_LIST,
    RECOMMEND, HELP, EXIT, CLEAR
}
