@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes add command with Name, Student ID, Class ID, Email;
if () then ([Invalid inputs])
  :Display error message in result;
else ([Valid inputs])
    : Creates a new Student object with the user inputs;
endif

stop

@enduml

