@startuml
!include ../style.puml

Participant ":JsonUtil" as ju STORAGE_COLOR
Participant ":MainWindow" as mw UI_COLOR
Participant ":LogicManager" as lm LOGIC_COLOR

activate lm
activate ju
activate mw
lm --> mw : DownloadCommandResult

ju <- mw
ju -> ju : Get JSON data
activate ju
ju --> mw : jsonData
deactivate ju

mw -> mw : prompt for destination
activate mw
mw -> ju :file
deactivate mw

ju -> ju : Write to Csv
activate ju
<-- ju
deactivate ju

@enduml
