@startuml
'https://plantuml.com/object-diagram
title: Initial State

object ApplicantBook
object PositionBook

map Start {
}

map PositionBook {
 Software Engineer: Writes code everyday
}

map ApplicantBook {
 John: Software Engineer, PENDING
 Jake: Software Engineer, REJECTED
 Alice: Software Engineer, REJECTED
}

Start -down-> ApplicantBook
Start -down-> PositionBook
@enduml
