@startuml
'https://plantuml.com/sequence-diagram

autonumber

Model -> Calculator: calculateRejectionRate()
activate Calculator

Calculator -> Calculator: calculateRejectionRate()
activate Calculator
Calculator -> ApplicantBook: (calculation occurs)
activate ApplicantBook

ApplicantBook -> Calculator: rejectionRate (as float)
deactivate ApplicantBook
deactivate Calculator

Calculator --> Model: Request complete
deactivate Calculator
@enduml
