@startuml
'https://plantuml.com/object-diagram
title: After command "rate Software Engineer"

object Calculator
object ApplicantBook
object PositionBook
object Model

map Start {
}

map PositionBook {
 Software Engineer: Writes code everyday

}

map ApplicantBook {
 John: Software Engineer, PENDING
 Jake: Software Engineer, REJECTED
 Alice: Software Engineer, REJECTED
}

map Model {
 calculateRejectionRate()
}

map Calculator {
 calculateRejectionRate()
}

Start -down-> ApplicantBook
Start -down-> PositionBook
Model -right-> Calculator
Calculator -right->ApplicantBook
@enduml
