@startuml
'https://plantuml.com/object-diagram
title: After verifying "Software Engineer"

object ApplicantBook
object PositionBook
object Model

map Start {
}

map PositionBook {
 Software Engineer: Writes code everyday

}

map ApplicantBook {
 John: Software Engineer, PENDING
 Jake: Software Engineer, REJECTED
 Alice: Software Engineer, REJECTED
}

map Model {
 hasPositionWithTitle()
}

Start -down-> ApplicantBook
Start -down-> PositionBook
Model -left-> PositionBook
@enduml
