@startuml
!include ../../../style.puml

box Logic LOGIC_COLOR_T1
participant ":HelpCommand" as hc LOGIC_COLOR
participant ":CommandResult" as cr LOGIC_COLOR
end box

box VersionedModel MODEL_COLOR_T1
participant ":VersionedModel" as vm MODEL_COLOR

end box

-> hc ++ : execute
hc -> vm : setAdditionalViewType(AdditionalViewType.HELP)
hc -> vm : setAdditionalInfo(AdditionalInfo.of(helpMessage))

alt isGeneralHelp
create cr
hc -> cr ++ : CommandResult(MESSAGE_HELP_SUCCESS_GENERAL, true, false)
cr --> hc -- : commandResult

else else


create cr
hc -> cr ++ : CommandResult(String.format(MESSAGE_HELP_SUCCESS_SPECIFIC, this.commandWord), true, false)
cr --> hc -- : commandResult

end
<-- hc -- : commandResult


@enduml
