@startuml
!include ../../../style.puml

box Logic LOGIC_COLOR_T1
Participant ":VisualizeCommand" as vc LOGIC_COLOR
Participant ":CommandResult" as result LOGIC_COLOR
end box

box VersionedModel MODEL_COLOR_T1
Participant ":VersionedModel" as mm MODEL_COLOR
Participant ":Student" as st MODEL_COLOR
Participant ":Assessment" as as MODEL_COLOR
end box

-> vc ++ :execute
vc -> mm ++:updateFilteredStudentList(PREDICATE_SHOW_ALL_STUDENTS)
deactivate
vc -> mm ++ :getFilteredStudentList()
return studentList
loop all students in studentList
    vc -> st ++ :getAssessment()
    return
    vc -> as ++ :getAssessmentHashMap()
    return
end

vc -> mm ++ :setAdditionalViewType(AdditionalViewType.VISUALIZE)
deactivate
vc -> mm ++ :setAdditionalInfo(AdditionalInfo.of(orderedAssessmentResults))
deactivate

create result
vc -> result ++ :CommandResult(MESSAGE_VISUALIZE_SUCCESS)
return commandResult
return commandResult
@enduml
