@startuml
!include ../../../style.puml

Participant ":AttendanceCommand" as ac LOGIC_COLOR
Participant ":ModelManager" as mm LOGIC_COLOR
Participant ":Student" as st LOGIC_COLOR
Participant ":StudioRecord" as sr LOGIC_COLOR
Participant ":Attendance" as at LOGIC_COLOR
Participant ":CommandResult" as cr LOGIC_COLOR

[-> ac : execute(model)
activate ac
ac -> mm ++: getFilteredStudentList
mm --> ac --: lastShownList

loop for each Index in indexArrayList


    ac -> st ++ : getAttendance
    st -> sr ++ : getAttendance
    sr --> st -- : attendanceToEdit
    st --> ac -- : attendanceToEdit
    ac -> at  : update(studioSession, attendanceStatus)
    ac -> st ++ : getParticipation
    st -> sr ++ : getParticipation
    sr --> st -- : participation
    st --> ac -- : participatiion
    ref over ac : UpdateModelAttendance
end loop

ac -> mm  : updateFilteredStudentsList(PREDICATE_SHOW_ALL_STUDENTS)


create cr
ac -> cr ++ : CommandResult(MESSAGE_UPDATE_ATTENDANCE_SUCCESS)
cr --> ac -- : command result
<-- ac : command result

@enduml
