@startuml
!include ../../../style.puml

Participant ":AttendanceCommand" as ac LOGIC_COLOR
Participant ":CommandException" as ce LOGIC_COLOR

activate ac

opt zero based index >= size of lastShownList
create ce
ac -> ce ++
ce --> ac -- : throw command exception
<- ac -- :throw command exception

end
ac--
@enduml
