@startuml
!include ../../../style.puml

Participant ":AttendanceCommand" as ac LOGIC_COLOR
Participant ":StudioRecord" as sr LOGIC_COLOR
Participant ":Student" as est LOGIC_COLOR
Participant ":ModelManager" as mm LOGIC_COLOR


activate ac
-> ac
create sr
ac -> sr ++ : StudioRecord(attendanceToEdit, participation)
sr --> ac -- : newStudioRecord


create est
ac -> est ++ :  Student(name, phone, email, telegram, newStudioRecord, assessment, tags)
est --> ac -- : editedStudent

ac -> mm ++ : setStudent(studentToEdit, editedStudent)
mm --> ac --
<-- ac
@enduml
