@startuml
!include style.puml
start
if () then ([Client with name already in InsurancePal])
    :Throw exception,
    signalling duplicate person;
else ([else])
    :Add client to InsurnacePal;
endif
stop
@enduml
