@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "<<class>>\nArgumentTokenizer" as ArgumentTokenizer LOGIC_COLOR
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "person:Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute(add n/Dylan p/97998581\n e/dylan.eyyou@gmail.com\n r/Pilot et/Full time s/3500\n l/PhD y/4)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(input)
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser : AddCommandParser()
activate AddCommandParser

AddCommandParser --> AddressBookParser
deactivate AddCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser: BUFFER_MESSAGE

AddressBookParser -> AddCommandParser : parse(add n/Dylan p/97998581\n e/dylan.eyyou@gmail.com\n r/Pilot et/Full time s/3500\n l/PhD y/4)
activate AddCommandParser

AddCommandParser -> ArgumentTokenizer : tokenize()
activate ArgumentTokenizer

ArgumentTokenizer --> AddCommandParser
deactivate ArgumentTokenizer

AddCommandParser -> AddCommandParser : arePrefixesPresent()
activate AddCommandParser

AddCommandParser --> AddCommandParser
deactivate AddCommandParser

create Person
AddCommandParser -> Person : Person()
activate Person

Person --> AddCommandParser
deactivate Person

create AddCommand
AddCommandParser -> AddCommand : AddCommand(person)
activate AddCommand

AddCommand --> AddCommandParser
deactivate

AddCommandParser --> AddressBookParser
deactivate

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser:
destroy AddCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : hasPerson(person)
activate Model

Model --> AddCommand
deactivate

AddCommand -> Model : addPerson(person)
activate Model

Model --> AddCommand
deactivate

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml

