@startuml
'https://plantuml.com/activity-diagram-beta

start
:User calls Add Employee command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command syntax is valid])
if () then ([input arguments are valid])

    :Parse input into the various fields
    required for Employee;

    :Create Employee;

    :AddEmployeeCommand is created
    and executed by LogicManager;

    :Update employee list with new employee;

    :Update UI;

    :Display success message to user with
    details of edited customer;

    stop

else ([else])
    endif
else ([else])
    endif
    :Display error to user;
stop

@enduml
