@startuml
!include style.puml

start
if () then ([group does not\n  already exist])
  :Add students to group <$rake> ;
  if () then ([no exceptions occurred])
    :Add group\nto database;
    :Update group list\nof students;
  else ([else])
    :Display an\nerror message;
  endif
else ([group already exists])
  :Display an\nerror message;
endif

stop

@enduml
