@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant "**classmate:Classmate**" as Classmate MODEL_COLOR
participant "**tutorialClasses:UniqueTutorialClassList**" as UniqueTutorialClassList MODEL_COLOR
participant TutorialClass as TutorialClass MODEL_COLOR
participant UniqueTutorialGroupList as UniqueTutorialGroupList MODEL_COLOR
end box


[-> Classmate : ""hasTutorialClass(tc)""
activate Classmate

Classmate -> UniqueTutorialClassList : ""contains(tc)""
activate UniqueTutorialClassList

UniqueTutorialClassList -> TutorialClass : ""check through tutorial class list""
activate TutorialClass


note right
""tc"" is the TutorialClass
that the TutorialGroup
being added to ClassMate
belongs to
end note

TutorialClass --> UniqueTutorialClassList
deactivate TutorialClass

UniqueTutorialClassList --> Classmate
deactivate UniqueTutorialClassList

[-> Classmate : ""hasTutorialGroup(tg)""

Classmate -> UniqueTutorialClassList : ""contains(tg)""
activate UniqueTutorialClassList

UniqueTutorialClassList -> TutorialClass : ""getClassCode(tg)""
activate TutorialClass
UniqueTutorialClassList -> TutorialClass : ""createTestTutorialClass(cc)""
note right
""cc"" is the ClassCode
of the TutorialClass
that the TutorialGroup is
being added to
end note
UniqueTutorialClassList -> TutorialClass : ""check for matching tutorial class""
UniqueTutorialClassList -> TutorialClass : ""getTutorialGroups()""

TutorialClass --> UniqueTutorialClassList
deactivate TutorialClass

UniqueTutorialClassList -> UniqueTutorialGroupList : ""check if tutorial group exists""
activate UniqueTutorialGroupList

UniqueTutorialGroupList --> UniqueTutorialClassList
deactivate UniqueTutorialGroupList

UniqueTutorialClassList --> Classmate
deactivate UniqueTutorialClassList

[-> Classmate : ""addTutorialGroup(tc)""

Classmate -> UniqueTutorialClassList : ""add(tg)""
activate UniqueTutorialClassList

UniqueTutorialClassList -> TutorialClass : ""getClassCode(tg)""
activate TutorialClass
UniqueTutorialClassList -> TutorialClass : ""createTestTutorialClass(tc)""
UniqueTutorialClassList -> TutorialClass : ""check for matching tutorial class""
UniqueTutorialClassList -> TutorialClass : ""getTutorialGroups()""

TutorialClass --> UniqueTutorialClassList
deactivate TutorialClass

UniqueTutorialClassList -> UniqueTutorialGroupList : ""add tutorial group""
activate UniqueTutorialGroupList

UniqueTutorialGroupList --> UniqueTutorialClassList
deactivate UniqueTutorialGroupList

UniqueTutorialClassList --> Classmate
deactivate UniqueTutorialClassList

@enduml
