@startuml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Final state

package TuitiONE <<rectangle>> {
    package Lessons <<rectangle>> {
        object "<u>l:Lesson" as Lesson {
            lessonCode = Science-P2-Wed-1200
            grade = P2
            size = 0
        }
    }
    package Students <<rectangle>> {
        object "<u>:Student" as Alice {
            name = Alice
            grade = P2
        }
        object "<u>:Student" as John {
            name = John
            grade = P2
        }
    }
}

John -[hidden]> Alice

@end
