@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddProductCommandParser" as AddProductCommandParser LOGIC_COLOR
participant "command:AddProductCommand" as AddProductCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add -p pen -$ 10.0 -q 120")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add -p pen -$ 10.0 -q 120", model)
activate AddressBookParser

create AddProductCommandParser
AddressBookParser -> AddProductCommandParser : AddProductCommandParser()
activate AddProductCommandParser

AddProductCommandParser --> AddressBookParser
deactivate AddProductCommandParser

AddressBookParser -> AddProductCommandParser : parse("pen -$ 10.0 -q 120")
activate AddProductCommandParser

create AddProductCommand
AddProductCommandParser -> AddProductCommand
activate AddProductCommand

AddProductCommand --> AddProductCommandParser : command
deactivate AddProductCommand

AddProductCommandParser --> AddressBookParser : command
deactivate AddProductCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddProductCommandParser [hidden]-> AddressBookParser
destroy AddProductCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> AddProductCommand : execute(model)
activate AddProductCommand

AddProductCommand -> Model : addProduct(productToAdd)
activate Model

Model --> AddProductCommand
deactivate Model

create CommandResult
AddProductCommand -> CommandResult
activate CommandResult

CommandResult --> AddProductCommand : result
deactivate CommandResult

AddProductCommand --> LogicManager : commandResult
deactivate AddProductCommand

[<-- LogicManager
deactivate LogicManager
@enduml
