@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuleTrackerParser" as ModuleTrackerParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add...")
activate LogicManager

LogicManager -> ModuleTrackerParser : parseCommand("add...")
activate ModuleTrackerParser

create AddCommandParser
ModuleTrackerParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> ModuleTrackerParser
deactivate AddCommandParser

ModuleTrackerParser -> AddCommandParser : parse(arguments)
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

AddCommandParser --> ModuleTrackerParser : a
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> ModuleTrackerParser
destroy AddCommandParser

ModuleTrackerParser --> LogicManager : a
deactivate ModuleTrackerParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addModule(1)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
