@startuml
!include style.puml

title: Add students to group

start
while () is ([has remaining student(s) to add])
  :Find matched student;
  if () then (    [one matched student found\nand student not already in group])
    :Add student\nto group;
  else ([else])
    :Display an\nerror message;
    stop
  endif
endwhile ([else])
stop

@enduml
