@startuml
!include style.puml
skinparam arrowThickness 1
skinparam arrowColor USER_COLOR
skinparam classBackgroundColor USER_COLOR
skinparam classBorderColor USER_COLOR

skinparam activity {
BorderColor #gold
DiamondBorderColor #gold
}

start
:User executes add command;
:Create and add new Client to UniqueClientList;
:Create or retrieve existing tags;
:Add tags to the client;
:Add the client to the tags;
:AddressBook Listener adds new tags to UniqueTagList;
:UniqueTagList fires an update event;
:UI Listener updates TagPanel UI;
stop
@enduml


