@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SportsPaParser" as SportsPaParser LOGIC_COLOR
participant ":ListMembersCommand" as ListMembersCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":AliasMap" as AliasMap MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("l")
activate LogicManager

LogicManager -> SportsPaParser : parseCommand("l")
activate SportsPaParser

SportsPaParser -> AliasMap : convertAliasIfPresent()
activate AliasMap
AliasMap --> SportsPaParser : "listm"
deactivate AliasMap

create ListMembersCommand
SportsPaParser -> ListMembersCommand
activate ListMembersCommand

ListMembersCommand --> SportsPaParser
deactivate ListMembersCommand

SportsPaParser --> LogicManager
deactivate SportsPaParser

LogicManager -> ListMembersCommand : execute()
activate ListMembersCommand

ListMembersCommand -> Model : updateFilteredMemberList(SHOW_ALL)
activate Model

Model --> ListMembersCommand
deactivate Model

create CommandResult
ListMembersCommand -> CommandResult
activate CommandResult

CommandResult --> ListMembersCommand
deactivate CommandResult

ListMembersCommand --> LogicManager : result
deactivate ListMembersCommand
ListMembersCommand -[hidden]-> LogicManager : result
destroy ListMembersCommand

[<--LogicManager
deactivate LogicManager
@enduml
