@startuml
!include style.puml

start
:Check input string is valid;
if () then (is empty string)
  :Create empty appointment object;

else (else)
  :Convert string to match formatter requirements;
  :Parse string into LocalDateTime object;
  :Create new appointment object containing meeting time;
endif
:Return new appointment object;

stop

@enduml
