@startuml
skinparam arrowThickness 1.1
skinparam arrowColor #000000
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
show fields

title Adding new Appointment

object "__:Person__" as normalHuman {
}

object "__:Appointment__" as completeAppointment {
    - date = "11 Oct 2022"
    - time = "1000"
    - venue = "NUS"
}

object "__:AppointmentCount__" as emptyAppointmentCount {
    - count = 0
}

normalHuman --> completeAppointment
normalHuman --> emptyAppointmentCount


@enduml
