@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Appointment <<Rectangle>>{
Class Appointment
Class Patient
Class Doctor
Class Duration
Class Session
Class Remark
}

Appointment *--> Patient
Appointment *--> Doctor
Appointment *--> Duration
Appointment *--> Session
Appointment *--> Remark

@enduml
