@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main #dcdcdc
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User #FFFFFF
Class "<$documents>" as File #FFFFFF


UI -[UI_COLOR_T1]> Logic
UI -right[UI_COLOR_T1]-> Model
Logic -[LOGIC_COLOR_T1]-> Storage
Logic -down[LOGIC_COLOR_T1]-> Model
Main -[MAIN_COLOR_T1]-> UI
Main -[MAIN_COLOR_T1]-> Logic
Main -[MAIN_COLOR_T1]-> Storage
Main -up[MAIN_COLOR_T1]-> Model
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR_T1].> Model
Storage .right[STORAGE_COLOR_T1].>File
User .down.> UI
@enduml
