@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ConthacksParser" as ConthacksParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete m/CS2103T")
activate LogicManager

LogicManager -> ConthacksParser : parseCommand("delete m/CS2103T")
activate ConthacksParser

create DeleteCommandParser
ConthacksParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ConthacksParser
deactivate DeleteCommandParser

ConthacksParser -> DeleteCommandParser : parse(" m/CS2103T")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> ConthacksParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ConthacksParser
destroy DeleteCommandParser

ConthacksParser --> LogicManager : d
deactivate ConthacksParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

loop no. of contacts with module code CS2103T
alt contact tagged to only CS2103T
DeleteCommand -> Model : deletePerson()
activate Model

Model --> DeleteCommand
deactivate Model
else contacts attached to other module codes
DeleteCommand -> Model : setPerson()
activate Model

Model --> DeleteCommand
deactivate Model
end
end

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
