@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueParticipantList
AddressBook *-down-> "1" UniqueEventList

UniqueParticipantList -down-> Participant
UniqueEventList -down-> "*" Event

Participant *--> Name
Participant *--> Phone
Participant *--> Email
Participant *--> Address
Participant *--> ParticipantId
Participant "*" <-left-> "*" Event
Participant --> "*" NextOfKin
Participant --> "0..1" BirthDate
Event *--> EventName
Event *--> EventDate
Event --> "0..1" EventTime
@enduml
