@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

SportsPa *-right-> "1" UniqueMemberList
SportsPa *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueMemberList
UniqueTagList -[hidden]down- UniqueMemberList

UniqueTagList *-right-> "      *" Tag
UniqueMemberList -right-> "~*all" Member

Member -up-> "        0..*" Tag

Member *--> "1" Name
Member *--> "1" Phone
Member *--> "1" Availability
Member *--> "1" TodayAttendance
Member *--> "1" TotalAttendance

SportsPa *--> "1" UniqueFacilityList
UniqueFacilityList --> "~*all" Facility
Facility *--> "1" FacilityName
Facility *--> "1" Capacity
Facility *--> "1" Location
Facility *--> "1" Time
Facility *--> "1" AllocationMap
AllocationMap *--> "1..*       " Member
@enduml
