@startuml
!include style.puml

Participant ":InsurancePalParser" as addressBookParser LOGIC_COLOR_T2
Participant ":ClaimCommandParser" as claimCommandParser LOGIC_COLOR
Participant "<<class>>\nParserUtil" as util MODEL_COLOR
Participant ":EditClaimDescriptor" as descriptor STORAGE_COLOR
Participant ":ClaimCommand" as command #purple

addressBookParser -[LOGIC_COLOR_T2]> claimCommandParser :"1 n/Car Accident \nd/At NTU s/pending"
activate addressBookParser LOGIC_COLOR_T2
activate claimCommandParser LOGIC_COLOR

claimCommandParser -[LOGIC_COLOR]> util :parseArguments;
activate util MODEL_COLOR

util -[MODEL_COLOR]-> claimCommandParser :Arguments
deactivate util

create descriptor
claimCommandParser -[LOGIC_COLOR]> descriptor :EditClaimDescriptor(Title, Description, Status)
activate descriptor STORAGE_COLOR

descriptor -[STORAGE_COLOR]-> claimCommandParser :EditClaimDescriptor
deactivate descriptor

create command
claimCommandParser -[LOGIC_COLOR]> command :ClaimCommand(Index, EditClaimDescriptor)
activate command #purple

command -[#purple]-> claimCommandParser :ClaimCommand
deactivate command

claimCommandParser -[LOGIC_COLOR]-> addressBookParser :ClaimCommand
deactivate claimCommandParser

deactivate addressBookParser
@enduml
