@startuml
!include style.puml
start
:Get client at index;
:Get client's set of claims;
:Find claim with the same title;

skinparam activity {
BackgroundColor<<Highlight>> LightBlue

}

if () then ([No such claim])
    :Create new claim \nfrom EditClaimDescriptor;
    <<Highlight>>:Add claim to client;
else ([else])
    if () then ([EditClaimDescriptor empty])
        <<Highlight>>:Remove claim \nfrom client;
    else ([else])
        :Create new claim \nwith updated fields;
        <<Highlight>>:Edit existing claim with \nupdated claim;
    endif
endif
:Return CommandResult;
stop
@enduml
