@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits Track2Gather])
    :Purge redundant states;
    :Save Track2Gather to
    track2GatherStateList;
else ([else])
endif
stop
@enduml
