@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class CommandResult

Class CommandWarning {
 isAscending: boolean
}

CommandResult "1" *-- "0..1" CommandWarning

@enduml
