@startuml
start
:User presses up arrow key;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Has successfully executed command(s) \nand currently not at oldest command])
        :Replace content in CommandBox based on\nrelative positioning of CommandHistory;
else ([else])
    :Content in CommandBox remains intact;

endif
stop
@enduml
