@startuml
!include style.puml
skinparam arrowThickness 1.1

package Logic {
Interface Logic <<Interface>> LOGIC_COLOR
Class LogicManager LOGIC_COLOR
}

package Model{
Interface Model <<Interface>> MODEL_COLOR
Class ModelManager MODEL_COLOR
}

package Storage{
Interface Storage <<Interface>> STORAGE_COLOR
Class StorageManager STORAGE_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside .[LOGIC_COLOR].> Logic

LogicManager .up[LOGIC_COLOR].|> Logic
ModelManager .up[MODEL_COLOR].|> Model
StorageManager .up[STORAGE_COLOR].|> Storage

LogicManager --> Model
LogicManager -[STORAGE_COLOR]-> Storage
@enduml
