@startuml
!include style.puml
box Logic #FFFFFF
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

skinparam sequenceBoxBorderColor #black

box Model #FFFFFF
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager LOGIC_COLOR

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser LOGIC_COLOR

create DeleteCommandParser LOGIC_COLOR
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser LOGIC_COLOR

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser LOGIC_COLOR

AddressBookParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser LOGIC_COLOR

create DeleteCommand LOGIC_COLOR
DeleteCommandParser -> DeleteCommand
activate DeleteCommand LOGIC_COLOR

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand LOGIC_COLOR

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser LOGIC_COLOR
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser LOGIC_COLOR

AddressBookParser --> LogicManager : d
deactivate AddressBookParser LOGIC_COLOR

LogicManager -> DeleteCommand : execute()
activate DeleteCommand LOGIC_COLOR

DeleteCommand -> Model : deleteClient(1)
activate Model MODEL_COLOR

Model --> DeleteCommand
deactivate Model LOGIC_COLOR

create CommandResult LOGIC_COLOR
DeleteCommand -> CommandResult
activate CommandResult LOGIC_COLOR

CommandResult --> DeleteCommand
deactivate CommandResult LOGIC_COLOR

DeleteCommand --> LogicManager : result
deactivate DeleteCommand LOGIC_COLOR

[<--LogicManager
deactivate LogicManager LOGIC_COLOR
@enduml
