Justin, [8/11/21 20:36]
@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters command: delete <index>;
switch()
case ([<index> is positive])
  :Is <index> <= number of contacts displayed?;
  if () then ([True])
    :Delete contact at <index>;
  else ([False])
    :Displays error message: "The contact index provided is out of range!";
  endif
case ([<index> is non-positive])
  :Displays error message: "Invalid command format";
endswitch


stop

@enduml
