@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteFolderCommandParser" as DeleteFolderCommandParser LOGIC_COLOR
participant "d:DeleteFolderCommand" as DeleteFolderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("rmdir CS2103")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("rmdir CS2103")
activate AddressBookParser

create DeleteFolderCommandParser
AddressBookParser -> DeleteFolderCommandParser
activate DeleteFolderCommandParser

DeleteFolderCommandParser --> AddressBookParser
deactivate DeleteFolderCommandParser

AddressBookParser -> DeleteFolderCommandParser : parse("CS2103")
activate DeleteFolderCommandParser

create DeleteFolderCommand
DeleteFolderCommandParser -> DeleteFolderCommand
activate DeleteFolderCommand

DeleteFolderCommand --> DeleteFolderCommandParser : d
deactivate DeleteFolderCommand

DeleteFolderCommandParser --> AddressBookParser : d
deactivate DeleteFolderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteFolderCommandParser -[hidden]-> AddressBookParser
destroy DeleteFolderCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteFolderCommand : execute()
activate DeleteFolderCommand

DeleteFolderCommand -> Model : deleteFolder(folderToRemove)
activate Model

Model --> DeleteFolderCommand
deactivate Model

create CommandResult
DeleteFolderCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteFolderCommand
deactivate CommandResult

DeleteFolderCommand --> LogicManager : result
deactivate DeleteFolderCommand

[<--LogicManager
deactivate LogicManager
@enduml
