@startuml
start
:user inputs delete command;
:Logic executes delete command;
:DeleteCommandParser parses the command;

if () then ([Delete index is with in the valid range])
    if() then ([Visit flag is present])
        if() then ([Person at specified index has a next visit])
            :deleteVisit;
        else ([else])
            :Throw CommandException;
        endif

    else ([else])

        :deletePerson;
    endif

else ([else])
    :Throw ParseException;

endif
stop

@enduml
