@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters delete appointment command with index;
:Parse command;
if (index is valid) then (true)
  : Create new DeleteAppointmentCommand;
  : Execute DeleteAppointmentCommand;
  : Remove target appointment;
else (false)
    : Generate Command Exception;
endif
: Display result to user;
stop

@enduml
