@startuml
start
:User executes Delete Marked Command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Retrieve filtered list of applicants
marked done ;

if () then ([filtered list is not empty])
:Delete marked applicants from model;
    :GUI Result Display updated with
    marked applicants that have been deleted;
else ([else])
    :GUI Result Display updated
    with message that there are no marked
    applicants and none have been deleted;
endif

stop
@enduml
