@startuml
skinparam wrapWidth 140
skinparam defaultTextAlignment center

start
:User inputs done command;
:Logic executes done command;
:DoneCommandParser parses the command;

if () then ([Visit date is in correct format])
    if () then ([Index is valid])
        if () then ([The elderly has a next visit])
            :Execute DoneCommand;
        else ([else])
            :Throw CommandException;
        endif

    else ([else])
        :Throw CommandException;
    endif

else ([else])
    :Throw ParseException;

endif
stop

@enduml
