@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TaskCommandsParser" as TaskCommandsParser LOGIC_COLOR
participant ":EditTaskCommandParser" as EditTaskCommandParser LOGIC_COLOR
participant ":EditTaskCommand" as EditTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("task -e 3 n/Report 4")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("task -e 3 n/Report 4")
activate AddressBookParser

AddressBookParser -> TaskCommandsParser : parseCommand("-e 3 n/Report 4")
activate TaskCommandsParser

create EditTaskCommandParser
TaskCommandsParser -> EditTaskCommandParser : parseCommand("3 n/Report 4")
activate EditTaskCommandParser

create EditTaskCommand
EditTaskCommandParser --> EditTaskCommand
activate EditTaskCommand

EditTaskCommand --> EditTaskCommandParser
deactivate EditTaskCommand

EditTaskCommandParser --> TaskCommandsParser
deactivate EditTaskCommandParser

TaskCommandsParser --> AddressBookParser
deactivate TaskCommandsParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> EditTaskCommand : execute()
activate EditTaskCommand

EditTaskCommand -> Model : setTask(taskToEdit, editedTask)
activate Model

Model --> EditTaskCommand
deactivate Model

create CommandResult
EditTaskCommand -> CommandResult
activate CommandResult

CommandResult --> EditTaskCommand
deactivate CommandResult

EditTaskCommand --> LogicManager : result
deactivate EditTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
