@startuml
!include style.puml

box Logic LOGIC_COLOR_T1


participant "c:EditContactCommand" as EditContactCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1



participant ":Model" as Model MODEL_COLOR

participant "toEdit:Contact" as ToEdit MODEL_COLOR
participant "edited:Contact" as Edited MODEL_COLOR

end box

[-> EditContactCommand : execute()

activate EditContactCommand

EditContactCommand -> Model : get contact to edit
activate Model

Model -> ToEdit
activate ToEdit
ToEdit --> Model: contact to edit
deactivate ToEdit

Model --> EditContactCommand : contact to edit
deactivate Model

EditContactCommand -> EditContactCommand : createEditedContact(contact to edit)
activate EditContactCommand

create Edited
EditContactCommand -> Edited
activate Edited
Edited --> EditContactCommand : edited contact
deactivate Edited
deactivate EditContactCommand

EditContactCommand -> Model : getPoliciesBelongingTo(contactToEdit)

activate Model
Model -> EditContactCommand : policies to edit
deactivate Model

EditContactCommand -> EditContactCommand: create new policies belonging to editedContact

EditContactCommand -> Model : replace policies to edit with new policies


EditContactCommand -> Model : setContact(edited contact)


EditContactCommand -[hidden]-> ToEdit
destroy ToEdit

[<-- EditContactCommand : commandResult
deactivate EditContactCommand
Model -[hidden]-> EditContactCommand

destroy EditContactCommand
@enduml
