@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditClientCommandParser" as EditClientCommandParser LOGIC_COLOR
participant "command:EditClientCommand" as EditClientCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit -c 1 -n Sora")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit -c 1 -n Sora", model)
activate AddressBookParser

create EditClientCommandParser
AddressBookParser -> EditClientCommandParser : EditClientCommandParser(model)
activate EditClientCommandParser

EditClientCommandParser --> AddressBookParser
deactivate EditClientCommandParser

AddressBookParser -> EditClientCommandParser : parse("1 -n Sora")
activate EditClientCommandParser

create EditClientCommand
EditClientCommandParser -> EditClientCommand
activate EditClientCommand

EditClientCommand --> EditClientCommandParser : command
deactivate EditClientCommand

EditClientCommandParser --> AddressBookParser : command
deactivate EditClientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditClientCommandParser [hidden]-> AddressBookParser
destroy EditClientCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> EditClientCommand : execute()
activate EditClientCommand

EditClientCommand -> Model : setClient(target, editedClient)
activate Model

Model --> EditClientCommand
deactivate Model

create CommandResult
EditClientCommand -> CommandResult
activate CommandResult

CommandResult --> EditClientCommand : result
deactivate CommandResult

EditClientCommand --> LogicManager : result
deactivate EditClientCommand

[<-- LogicManager
deactivate LogicManager
@enduml
