@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ENCRYPTION_COLOR
skinparam classBackgroundColor ENCRYPTION_COLOR

Package Encryption <<Rectangle>>{
Interface Cryptable <<Interface>>
Class Cryptor
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Cryptable

Cryptor .up.|> Cryptable
@enduml
