@startuml

title Final state

package Tuitione {
    package Lessons {
        object __Lesson__ {
        lessonCode = Math-P2-Wed-1800
        grade = P2
        size = 1
        }
    }
    package Students {
        object __Student__ {
        Name = Alice
        Grade = P2
        }
    }

    __Lesson__ <-R-> __Student__

}

@end
