@startuml

title Final state

package TuitiONE <<rectangle>> {
    package Lessons <<rectangle>> {
        object "<u>l1:Lesson" as Lesson{
        lessonCode = Math-P2-Wed-1800
        grade = P2
        size = 1
        }
    }
    package Students <<rectangle>> {
        object "<u>s1:Student" as Student {
        name = Alice
        grade = P2
        }
    }

    Lesson <-R-> Student

}

@end
