@startuml
start
:User executes Filter Interview Command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command is
valid with valid input])

    if () then ([input is 'past'])
    :List of applicants filtered
    for those with interviews that have
    passed;

    else ([input is 'future'])
    :List of applicants filtered
    for those with interviews that are
    upcoming;
    endif

    :GUI updates with filtered applicants;


else([else])
:GUI updates with error message
indicating invalid input;

endif
stop
@enduml
