@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterEventCommandParser" as FilterEventCommandParser LOGIC_COLOR
participant "f:FilterEventCommand" as FilterEventCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filterEvents d/2021-8-20"))
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("filterEvents d/2021-8-20")
activate AddressBookParser

create FilterEventCommandParser
AddressBookParser -> FilterEventCommandParser

activate FilterEventCommandParser
FilterEventCommandParser --> AddressBookParser
deactivate FilterEventCommandParser

AddressBookParser -> FilterEventCommandParser : parse(" d/2021-8-20")
activate FilterEventCommandParser

create FilterEventCommand
FilterEventCommandParser -> FilterEventCommand
activate FilterEventCommand

FilterEventCommand --> FilterEventCommandParser : f
deactivate FilterEventCommand

FilterEventCommandParser --> AddressBookParser : f
deactivate FilterEventCommandParser

FilterEventCommandParser -[hidden]-> AddressBookParser
destroy FilterEventCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FilterEventCommand : execute()
activate FilterEventCommand

FilterEventCommand -> Model : updateFilteredEventList(e)
activate Model

Model --> FilterEventCommand
deactivate Model

create CommandResult
FilterEventCommand -> CommandResult

activate CommandResult
CommandResult --> FilterEventCommand

deactivate CommandResult

FilterEventCommand --> LogicManager : result
deactivate
FilterEventCommand -[hidden]-> LogicManager : result
destroy FilterEventCommand

[<--LogicManager
deactivate LogicManager
@enduml
