@startuml
!include style.puml

mainframe **sd**  execution continues

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "f:FilterApplicantCommand" as FilterApplicantCommand LOGIC_COLOR
participant "d:FilterApplicantDescriptor" as FilterApplicantDescriptor LOGIC_COLOR
participant ":FilterApplicant\nDescriptorVerifier" as FilterApplicantDescriptorVerifier LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p:ApplicantMatches\nFiltersPredicate" as ApplicantMatchesFiltersPredicate MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute()
activate LogicManager

LogicManager -> FilterApplicantCommand ++ : execute(m)

FilterApplicantCommand -> FilterApplicantDescriptorVerifier ** : new FilterApplicantDescriptorVerifier(m, d)
activate FilterApplicantDescriptorVerifier
return
|||

FilterApplicantCommand -> ApplicantMatchesFiltersPredicate ** : new ApplicantMatchesFiltersPredicate(d)
activate ApplicantMatchesFiltersPredicate
ApplicantMatchesFiltersPredicate --> FilterApplicantCommand -- : p
|||

FilterApplicantCommand -> Model : updateApplicantFilteredList(p)
activate Model
return

return result
destroy FilterApplicantCommand
destroy FilterApplicantDescriptorVerifier

[<-- LogicManager --

@enduml
