@startuml
!include style.puml
start
:User enters find member command;
:Parse command word;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command word is an alias])
    :Replace shortcut with
    actual command word;
else ([else])
endif
:Parse command arguments;
if () then ([arguments are valid])
: Generate predicate based on
the attribute keywords specified;
    :Execute find member command;
:Update member list;
:Display member list;
stop
else ([else])
:Throw ParseException;
stop
@enduml
