@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "f:FindCommand" as FindCommand LOGIC_COLOR
participant "p:PersonMatchesKeywordsPredicate" as PersonMatchesKeywordsPredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find n/John t/unpaid")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("find n/John t/unpaid")
activate AddressBookParser

create FindCommandParser
AddressBookParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> AddressBookParser
deactivate FindCommandParser

AddressBookParser -> FindCommandParser : parse("n/John doe t/unpaid")
activate FindCommandParser

create PersonMatchesKeywordsPredicate

FindCommandParser -> PersonMatchesKeywordsPredicate
activate PersonMatchesKeywordsPredicate

PersonMatchesKeywordsPredicate --> FindCommandParser : p
deactivate PersonMatchesKeywordsPredicate

create FindCommand
FindCommandParser -> FindCommand : FindCommand(p)
activate FindCommand

FindCommand --> FindCommandParser : f
deactivate FindCommand

FindCommandParser --> AddressBookParser : f
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> AddressBookParser
destroy FindCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FindCommand : execute()
activate FindCommand

FindCommand -> Model : handle update FilteredPersonList logic
activate Model

note bottom
Details of updating FilteredPersonList logic is given in another diagram
end note

Model --> FindCommand
deactivate Model

FindCommand --> LogicManager : result
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml

