@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR




package Lesson <<Rectangle>>{
Class Lesson
Class Capacity
Class LessonName
Class Price
Class Students
Class Timing
Class Student
}

Lesson *--> "1" Capacity
Lesson *--> "1" LessonName
Lesson *--> "1" Price
Lesson *--> "1" Students
Lesson *--> "1" Timing

Students --> "*" Student


@enduml
