@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam nodesep 110

package "Lesson" {
    Class "{abstract}\nLesson" as Lesson
    Class RecurringLesson
    Class MakeUpLesson
    Class Date
    Class TimeRange
    Class Subject
    Class Homework
    Class LessonRates
    Class OutstandingFees
}

Lesson *-up-> "cancelledDates \n *" Date
Lesson *-up-> "endDate \n 1" Date
Lesson *-up-> "startDate \n 1" Date
Lesson *-up-> TimeRange
Lesson *-up-> Subject
Lesson *-up-> "1" LessonRates
Lesson *-up-> "1" OutstandingFees
Lesson *-up-> "*" Homework

Homework -[hidden]left-> Date
Subject -[hidden]left-> LessonRates
TimeRange -[hidden]left->LessonRates
Date -[hidden]left->Subject

Lesson <|-down- RecurringLesson
Lesson <|-down- MakeUpLesson

@enduml
