@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
    package Parser {
    Class FastParser
    Class XYZCommandParser
    }

    package Command {
    Class CommandResult
    Class "{abstract}\nCommand" as Command
    Class XYZCommand
    }


Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

package Storage{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .left.|> Logic

XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >

LogicManager -down-|> FastParser
FastParser .down.> XYZCommandParser : creates >
XYZCommandParser .left.> XYZCommand : creates >
@enduml
