@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkingCommandParser" as MarkingCommandParser LOGIC_COLOR
participant ":MarkCommand" as MarkCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("mark 1 2")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("mark 1 2")
activate AddressBookParser

create MarkingCommandParser



AddressBookParser -> MarkingCommandParser: MarkingCommandParser("mark")
activate MarkingCommandParser

MarkingCommandParser --> AddressBookParser

deactivate MarkingCommandParser

AddressBookParser -> MarkingCommandParser : parse(" 1 2")
activate MarkingCommandParser

create MarkCommand
MarkingCommandParser -> MarkCommand : MarkCommand([2,1])
activate MarkCommand

MarkCommand --> MarkingCommandParser :
deactivate MarkCommand

MarkingCommandParser --> AddressBookParser :
deactivate MarkingCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
MarkingCommandParser -[hidden]-> AddressBookParser:
destroy MarkingCommandParser

AddressBookParser --> LogicManager :
deactivate AddressBookParser

LogicManager -> MarkCommand : execute()
activate MarkCommand

MarkCommand -> Model : getFilteredPersonList()
activate Model
Model --> MarkCommand
deactivate Model

loop until list of indices ends
    MarkCommand -> Model: checkForMarkedPerson(personToCheck)
    activate Model
    Model --> MarkCommand:
    deactivate Model
end

loop until list of indices ends
    MarkCommand -> Model: markPerson(personToMark)
    activate Model
    Model --> MarkCommand:
    deactivate Model
end

create CommandResult
MarkCommand -> CommandResult
activate CommandResult
CommandResult --> MarkCommand
deactivate CommandResult

MarkCommand --> LogicManager: result
deactivate MarkCommand



[<--LogicManager
deactivate LogicManager
@enduml
