@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Class Model
Class ModelManager

Class Inventory
Class TransactionList
Class BookKeeping
Class Order
Class UniqueItemList
Class TransactionRecord
Class Item {
    -name: Name
    -id: Integer
    -salePrice: Double
    -costPrice: Double
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


ModelManager .up.|> Model
ModelManager -left-> "1" BookKeeping
ModelManager --> "1" Inventory
ModelManager -right-> "1" TransactionList
ModelManager --> "0..1" Order
TransactionList o-down-> "*" TransactionRecord

Inventory .right.> Order

Order *--> "1" UniqueItemList
Inventory *--> "1" UniqueItemList
TransactionRecord o--> "*" Item
TransactionRecord .left.|> Order

UniqueItemList o-right- "*" Item
Item .up.|> Order

@enduml