@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniqueEventList
Class UniqueParticipantList
Class Participant
Class Address
Class Email
Class Name
Class Phone
Class ParticipantId
Class BirthDate
Class NextOfKin
Class Event
Class EventName
Class EventDate
Class EventTime

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueParticipantList
AddressBook *--> "1" UniqueEventList
UniqueEventList --> "~* all" Event
Event *--> EventName
Event *--> EventDate
Event --> "0..1" EventTime
UniqueParticipantList --> "~* all" Participant
Participant *--> Name
Participant *--> Phone
Participant *--> Email
Participant *--> Address
Participant *--> ParticipantId
Participant --> "0..1" BirthDate
Participant --> "*" NextOfKin
Participant "*" <-left-> "*" Event

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Participant
ModelManager -->"~* filtered" Event
@enduml
