@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam UiBackgroundColor UI_COLOR
skinparam genericDisplay old
skinparam defaultFontSize 20

Package Model {
Class ObservableList<Friend> <<Interface>> MODEL_COLOR
Class FriendsList MODEL_COLOR

Package friend {
Class UniqueFriendsList MODEL_COLOR
}

Class FilteredList<Friend> MODEL_COLOR
Class SortedList<Friend> MODEL_COLOR
}

Package UI {
Class FriendListPanel UI_COLOR
}

FriendsList *-down-> "1" UniqueFriendsList
FriendsList -[hidden]right-- SortedList
UniqueFriendsList *-down-> "1" ObservableList
FilteredList *-down-> "1" ObservableList
SortedList *-down-> "1" FilteredList

FriendListPanel .-left-> ObservableList UI_COLOR

@enduml
