@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam defaultFontSize 18

Package Model <<Rectangle>>{
Interface ReadOnlyFriendsList <<Interface>>
Interface ReadOnlyGamesList <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class FriendsList
Class GamesList
Class ReadOnlyFriendsList
Class ReadOnlyGamesList
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Package friend <<Rectangle>> {
Class UniqueFriendsList
Class Friend
Class FriendId
Class FriendName
Class Schedule
Class Day
Class DayOfWeek
}

Package game <<Rectangle>> {
Class UniqueGamesList
Class Game
Class GameId
}

Package gamefriendlink {
Class GameFriendLink
Class UserName
Class SkillValue
FriendId "*" - "*" GameId
(FriendId, GameId) . GameFriendLink
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FriendsList .up.|> ReadOnlyFriendsList
GamesList .up.|> ReadOnlyGamesList

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .right.> ReadOnlyGamesList
Model .left.> ReadOnlyFriendsList
ModelManager -right-> "1" UserPrefs
ModelManager -right-> "1" GamesList
ModelManager -left-> "1" FriendsList
UserPrefs .up.|> ReadOnlyUserPrefs


FriendsList *--> "1" UniqueFriendsList
UniqueFriendsList ---> "*" Friend : all
Friend *--> "1" FriendName
Friend *--> "1" FriendId
Friend *--> "1" Schedule
Friend *-> "*" GameFriendLink

Schedule *--> "7" Day
Day *--> "1" DayOfWeek
FriendName -[hidden]right-> FriendId
Schedule -[hidden]right-> FriendName

GamesList *--> "1" UniqueGamesList
UniqueGamesList ---> "*" Game : all
Game *--> "1" GameId

GameFriendLink *--> "1" UserName
GameFriendLink *--> "1" SkillValue

ModelManager ---> "*" Friend : filtered
ModelManager ---> "*" Friend : filteredAndSorted
ModelManager ---> "*" Game : filtered

@enduml
