@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyInventory <<Interface>>
Interface Model <<Interface>>
Interface Displayable <<Interface>>
Class Inventory
Class ReadOnlyInventory
Class Model
Class ModelManager
Class Order
Class UniqueItemList
Class TransactionRecord
Class Item
Class ItemCard
Class TransactionCard

Class Item {
    -name: Name
    -id: Integer
    -salePrice: Double
    -costPrice: Double
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Model .right.> Displayable
Model .left.> ReadOnlyInventory

ModelManager .up.|> Model
ModelManager -left-> "1" Inventory
ModelManager -right-> "0..1" Order
ModelManager --> "*" TransactionRecord

Inventory .right.> Order

Inventory .up.|> ReadOnlyInventory

Order *--> "1" UniqueItemList
Inventory *--> "1" UniqueItemList

UniqueItemList -right-> "~* all" Item
ModelManager -right->"~* filtered" Item


Item .up.|> Displayable
TransactionRecord -[hidden]right- Item
TransactionRecord .up.|> Displayable

TransactionRecord .up.|> Order
Item .up.|> Order

Item .down.> ItemCard
TransactionRecord .down.> TransactionCard


@enduml
