@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Class Model
Class ModelManager

Class Inventory
Class TransactionList
Class Order
Class UniqueItemList
Class TransactionRecord {
    -id: String
    -timestamp: Instant
}
Class Item {
    -name: Name
    -id: Integer
    -salePrice: Double
    -costPrice: Double
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


ModelManager .up.|> Model
ModelManager ---> "1" Inventory
ModelManager ---> "1" TransactionList
ModelManager ---> "0..1\nopen\n order" Order
TransactionList o-down-> "*" TransactionRecord

Inventory .right.> Order

Order *--> "1" UniqueItemList
Inventory *--> "1" UniqueItemList
TransactionRecord -left-|> Order

UniqueItemList o-down- "*" Item


@enduml
