@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam objectBackgroundColor MODEL_COLOR
Package Model <<Rectangle>>{

Object "<u>filtered: FilteredList<Displayable></u>" as filtered
Object "<u>displayed: ObservableList<Displayable></u>" as displayed
Object "<u>displayList: DisplayList</u>" as displayList
Object "<u>source: ObservableList<Displayable></u>" as source

}
Package Ui <<Rectangle>>{
Object "<u>displayListView: ListView<Displayable></u>" as displayListView
Object "<u>displayListPanel: DisplayListPanel</u>" as displayListPanel
}

displayListPanel *-up-> displayListView
displayListView -left- filtered: observes >

displayed -up- filtered: updates >
displayList *-down-> displayed: updates >
displayList *-right-> filtered
displayList o-down- source: observes >

@enduml
