@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

Class modelManager as "__modelManager:ModelManager__"

Class optionalOrder as "__optionalOrder:OptionalOrder__"

Class transactions as "__transactions:List<TransactionRecord>__"

Class trans1 as "__transactionRecord1:TransactionRecord__"
Class item1Trans1 as "__pencil:Item__"
Class item2Trans2 as "__pen:Item__"
item2Trans2 -up-> trans1
item1Trans1 -up-> trans1


transactions -up-> modelManager
optionalOrder -up-> modelManager
trans1 -up-> transactions

@end
