@startuml
start
:AddressBookParser parses command;

:Command word and arguments parsed;

if () then ([Command word is valid])
else ([else])
    :Throw ParseException;
    stop
endif

while () is ([Command word is an alias])
    :Replace aliased command word with the default command word;
endwhile ([else])

if () then ([Command requires arguments])
    :Parse arguments;
    if () then ([Arguments are valid])
        :Create the command;
    else ([else])
        :Throw ParseException;
        stop
    endif
else ([else])
    :Create the command;
endif

:Execute the newly created command;

stop
@enduml
