@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand
Class ABCCommand

package "Parser classes"{
Interface Parser <<Interface>>
Interface ParserRequiringPersonList <<Interface>>
Class ContactsTabParser
Class XYZCommandParser
Class ABCCommandParser
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> ContactsTabParser

ContactsTabParser .down.> XYZCommandParser: creates >
ContactsTabParser .down.> ABCCommandParser: creates >

XYZCommandParser .right.> XYZCommand : creates >
ABCCommandParser .right.> ABCCommand : creates >
ContactsTabParser .right.> Command : returns >
XYZCommandParser .right.|> Parser
ParserRequiringPersonList -up-|> Parser
ABCCommandParser .up.|> ParserRequiringPersonList
XYZCommand -up-|> Command
ABCCommand -up-|> Command
note right of ABCCommandParser: ABCCommandParser = Parsers that require \naccess to the person list\nAssignPersonCommand, EditTaskCommand, etc


@enduml
