@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TutorAidParser" as TutorAidParser LOGIC_COLOR
participant ":PaidCommandParser" as PaidCommandParser LOGIC_COLOR
participant ":PaidCommand" as PaidCommand LOGIC_COLOR
end box

[-> LogicManager : execute("paid 2")
activate LogicManager

LogicManager -> TutorAidParser : parseCommand("paid 2")
activate TutorAidParser

create PaidCommandParser
TutorAidParser -> PaidCommandParser
activate PaidCommandParser

PaidCommandParser --> TutorAidParser
deactivate PaidCommandParser

TutorAidParser -> PaidCommandParser : parse("2")
activate PaidCommandParser

create PaidCommand
PaidCommandParser -> PaidCommand
activate PaidCommand

PaidCommand --> PaidCommandParser
deactivate PaidCommand

PaidCommandParser --> TutorAidParser
deactivate PaidCommandParser

TutorAidParser --> LogicManager
deactivate TutorAidParser

@enduml
