@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ConthacksParser" as ConthacksParser LOGIC_COLOR
participant ":AddModuleLessonCommandParser" as AddPersonCommandParser LOGIC_COLOR
participant "a:AddModuleLessonCommand" as AddPersonCommand LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
end box

[-> LogicManager : execute("addc ... m/CS2103T B04\nm/CS2100 T19 B09")
activate LogicManager

LogicManager -> ConthacksParser : parseCommand("addc ... m/CS2103T B04\nm/CS2100 T19 B09")
activate ConthacksParser

create AddPersonCommandParser
ConthacksParser -> AddPersonCommandParser
activate AddPersonCommandParser

AddPersonCommandParser --> ConthacksParser
deactivate AddPersonCommandParser

ConthacksParser -> AddPersonCommandParser : parse("... m/CS2103T B04\nm/CS2100 T19 B09")
activate AddPersonCommandParser

AddPersonCommandParser -> ParserUtil : parseModuleCodeForModuleLesson()
activate ParserUtil
ParserUtil -> AddPersonCommandParser : moduleCode
note right of AddPersonCommandParser : modulecode = [CS2100 T19]

deactivate ParserUtil

create AddPersonCommand
AddPersonCommandParser -> AddPersonCommand
activate AddPersonCommand

AddPersonCommand --> AddPersonCommandParser : a
deactivate AddPersonCommand

AddPersonCommandParser --> ConthacksParser : a
deactivate AddPersonCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddPersonCommandParser -[hidden]-> ConthacksParser
destroy AddPersonCommandParser

ConthacksParser --> LogicManager : a
deactivate ConthacksParser
@enduml
