@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TutorAidParser" as TutorAidParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":AddProgressCommandParser" as AddProgressCommandParser LOGIC_COLOR
participant "a:AddProgressCommand" as AddProgressCommand LOGIC_COLOR
end box

[-> LogicManager : execute("add -p 2 Did Homework")
activate LogicManager

LogicManager -> TutorAidParser : parseCommand("-p 2 Did Homework")
activate TutorAidParser

TutorAidParser -> AddCommandParser : parse("-p 2 Did Homework")
activate AddCommandParser

AddCommandParser -> AddProgressCommandParser : parse("2 Did Homework")
activate AddProgressCommandParser

create AddProgressCommand
AddProgressCommandParser -> AddProgressCommand : AddProgressCommand(targetIndex, progress)
activate AddProgressCommand
AddProgressCommandParser <-- AddProgressCommand : a
deactivate AddProgressCommand

AddCommandParser <-- AddProgressCommandParser : a
deactivate AddProgressCommandParser

TutorAidParser <-- AddCommandParser : a
deactivate AddCommandParser

LogicManager <-- TutorAidParser : a
deactivate TutorAidParser
@enduml
