@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Encryption
participant "temp:EncryptionManager" as EncryptionManager1 ENCRYPTION_COLOR
participant "new:EncryptionManager" as EncryptionManager2 ENCRYPTION_COLOR
end box

participant "<color:#red>**<<class>>**\n<color:#black>FileUtil" as FileUtil

[-> LogicManager : executePasswordCommand(...)
activate LogicManager

create EncryptionManager1
LogicManager -> EncryptionManager1
activate EncryptionManager1

EncryptionManager1 --> LogicManager
deactivate EncryptionManager1

create EncryptionManager2
LogicManager -> EncryptionManager2
activate EncryptionManager2

EncryptionManager2 --> LogicManager
deactivate EncryptionManager2

LogicManager -> EncryptionManager1  : decrypt()
activate EncryptionManager1

EncryptionManager1 --> LogicManager
deactivate EncryptionManager1

LogicManager -> EncryptionManager2 : encrypt()
activate EncryptionManager2

EncryptionManager2 --> LogicManager
deactivate EncryptionManager2

LogicManager -> FileUtil : deleteFile()
activate FileUtil

FileUtil --> LogicManager
deactivate FileUtil

[<--LogicManager
deactivate LogicManager
@enduml
