@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters command: pin 3;
switch()
case ([Contact at index 3 exists])
  :CONNECTIONS checks if contact is already pinned;
  if () then ([Contact not yet pinned])
    : CONNECTIONS pin contact to top of contact list;
    -CONNECTIONS displays contact details
  else ([Contact already pinned])
    : CONNECTIONS displays message: "Contact is already pinned!";
  endif
case ([No contact at index 3])
  :CONNECTIONS displays error message: "The contact index provided is out of range.";
endswitch


stop

@enduml