@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters command: pin <index>;
switch()
case ([Contact at specified index exists])
  :CONNECTIONS retrieves contact at specified index;
  -CONNECTIONS checks if contact is already pinned
  if () then ([Contact not yet pinned])
    :CONNECTIONS pin contact to top of contact list;
    -CONNECTIONS displays success message with contact details
  else ([Contact already pinned])
    :CONNECTIONS displays message: "Contact is already pinned!";
  endif
case ([No contact at specified index])
  :CONNECTIONS displays error message: "The contact index provided is out of range.";
endswitch


stop

@enduml
