@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":ProfileSetUpWindow" as ProfileSetUpWindow UI_COLOR
participant ":UiPart" as UiPart UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "<<Class>> \n Name" as Name MODEL_COLOR
participant "<<Class>> \n Telegram" as Telegram MODEL_COLOR
end box

[-> ProfileSetUpWindow : start()
activate ProfileSetUpWindow

ProfileSetUpWindow -> LogicManager : isProfilePresent()
activate LogicManager

LogicManager --> ProfileSetUpWindow : (Not Present - false)
deactivate LogicManager

ProfileSetUpWindow -> UiPart : getRoot()
activate UiPart

UiPart --> ProfileSetUpWindow
deactivate UiPart

opt Submit

ProfileSetUpWindow -> ProfileSetUpWindow : submit()
activate ProfileSetUpWindow

ProfileSetUpWindow -> ProfileSetUpWindow : areUserCredentialsValid()
activate ProfileSetUpWindow

ProfileSetUpWindow -> Name : isValidName(userName)
activate Name

Name --> ProfileSetUpWindow
deactivate Name

ProfileSetUpWindow -> Telegram : Telegram.isValidTelegram(userTelegram)
activate Telegram

Telegram --> ProfileSetUpWindow : false
deactivate Telegram

ProfileSetUpWindow -> ProfileSetUpWindow : setErrorMessageText(INVALID_TELEGRAM_MESSAGE)
activate ProfileSetUpWindow

ProfileSetUpWindow --> ProfileSetUpWindow
deactivate ProfileSetUpWindow

ProfileSetUpWindow --> ProfileSetUpWindow : false
deactivate ProfileSetUpWindow

ProfileSetUpWindow --> ProfileSetUpWindow
deactivate ProfileSetUpWindow

<-- ProfileSetUpWindow
deactivate ProfileSetUpWindow

@enduml