@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":ProfileSetUpWindow" as ProfileSetUpWindow UI_COLOR
participant ":UiPart" as UiPart UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

[-> MainWindow : show()
activate MainWindow

create ProfileSetUpWindow
MainWindow -> ProfileSetUpWindow : new ProfileSetUpWindow(stage, mainWindow, logic)
activate ProfileSetUpWindow

ProfileSetUpWindow --> MainWindow
deactivate ProfileSetUpWindow

MainWindow -> ProfileSetUpWindow : start()
activate ProfileSetUpWindow

ProfileSetUpWindow -> LogicManager : isProfilePresent()
activate LogicManager

LogicManager --> ProfileSetUpWindow
deactivate LogicManager

alt Profile is present

ProfileSetUpWindow --> MainWindow : start()

else Profile is not present

ProfileSetUpWindow -> UiPart : getRoot()
activate UiPart

UiPart --> ProfileSetUpWindow
deactivate UiPart

opt submit

ProfileSetUpWindow -> ProfileSetUpWindow : submit()
activate ProfileSetUpWindow

ProfileSetUpWindow -> LogicManager : setUserProfile(user)
activate LogicManager

LogicManager --> ProfileSetUpWindow
deactivate LogicManager

ProfileSetUpWindow -> ProfileSetUpWindow : close()
activate ProfileSetUpWindow

ProfileSetUpWindow --> ProfileSetUpWindow
deactivate ProfileSetUpWindow

ProfileSetUpWindow --> MainWindow : start()

ProfileSetUpWindow --> ProfileSetUpWindow
deactivate ProfileSetUpWindow

ProfileSetUpWindow --> MainWindow
deactivate ProfileSetUpWindow

end

end

<-- MainWindow
deactivate MainWindow

@enduml
