@startuml
!include style.puml
skinparam defaultFontSize 20

box Logic LOGIC_COLOR_T1
participant ":RecommendCommand" as RecommendCommand LOGIC_COLOR
participant ":FriendRecommendFilterPredicate" as FriendRecommendFilterPredicate LOGIC_COLOR
participant "friendSkillValueComparator:Comparator" as Comparator LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

-> RecommendCommand: execute(model)
activate RecommendCommand

create FriendRecommendFilterPredicate
RecommendCommand -> FriendRecommendFilterPredicate: new FriendRecommendFilterPredicate()
activate FriendRecommendFilterPredicate

RecommendCommand <-- FriendRecommendFilterPredicate
deactivate FriendRecommendFilterPredicate

create Comparator
RecommendCommand -> Comparator: new Comparator<Friend>()
activate Comparator

RecommendCommand <-- Comparator
deactivate Comparator

ref over RecommendCommand, Model: Updating of filtered and sorted friends list

@enduml
