@startuml
!include style.puml

Participant ":AddressBookParser" as addressBookParser LOGIC_COLOR_T2
Participant ":RevenueCommandParser" as revenueCommandParser LOGIC_COLOR
Participant "argMultimap:ArgumentMultimap" as argumentMultimap LOGIC_COLOR_T1
Participant "<<class>>\nParserUtil" as util LOGIC_COLOR_T3
Participant "revenue:Revenue" as revenue MODEL_COLOR
Participant ":Money" as money MODEL_COLOR
Participant ":RevenueCommand" as command LOGIC_COLOR_T4


addressBookParser -[LOGIC_COLOR_T2]> revenueCommandParser : parse("1 r/100.21")
activate addressBookParser LOGIC_COLOR_T2
activate revenueCommandParser LOGIC_COLOR

create argumentMultimap
revenueCommandParser -[LOGIC_COLOR]> argumentMultimap : ArgumentTokenizer.tokenize("1 r/100.21", PREFIX_REVENUE)
activate argumentMultimap LOGIC_COLOR_T1

argumentMultimap -[LOGIC_COLOR]-> revenueCommandParser
deactivate argumentMultimap

revenueCommandParser -[LOGIC_COLOR]> util :parseIndex(argMultimap.getPreamble())
activate util LOGIC_COLOR_T3

util -[LOGIC_COLOR]> argumentMultimap:getPreamble()
activate argumentMultimap LOGIC_COLOR_T1

argumentMultimap -[LOGIC_COLOR]-> util
deactivate argumentMultimap

util -[LOGIC_COLOR_T3]-> revenueCommandParser :index
deactivate util

revenueCommandParser -[LOGIC_COLOR]> util :parseRevenue(argMultimap.getValue(PREFIX_REVENUE).get())
activate util LOGIC_COLOR_T3

util -[LOGIC_COLOR]> argumentMultimap:getValue(PREFIX_REVENUE).get()
activate argumentMultimap LOGIC_COLOR_T1

argumentMultimap -[LOGIC_COLOR]-> util
deactivate argumentMultimap

create revenue
util -[LOGIC_COLOR_T3]-> revenue: Revenue(new Money(number))
activate revenue MODEL_COLOR

create money
revenue -[LOGIC_COLOR_T3]> money: Money(number)
activate money MODEL_COLOR

money -[LOGIC_COLOR_T3]-> revenue
deactivate money

revenue -[MODEL_COLOR]-> util
deactivate revenue

util -[LOGIC_COLOR_T3]-> revenueCommandParser
deactivate util

create command
revenueCommandParser -[LOGIC_COLOR]> command :RevenueCommand(index, revenue)
activate command LOGIC_COLOR_T4

command -[LOGIC_COLOR_T4]-> revenueCommandParser : RevenueCommand
deactivate command

revenueCommandParser -[LOGIC_COLOR]-> addressBookParser: RevenueCommand
deactivate revenueCommandParser

deactivate addressBookParser

@enduml
