@startuml
'https://plantuml.com/object-diagram

title After command "roster 1"

package TuitiONE <<rectangle>> {

    package filteredLessonList <<rectangle>> {
        object "<u>l1:Lesson" as Lesson1 {
        lessonCode = Math-P4-Wed-1800
        lessonListIndex = 1
        }
    }

    package filteredStudentList <<rectangle>> {
        object "<u>s1:Student" as Student1 {
        name = Bernice
        lesson(s) = Math-P4-Wed-1800
        }
    }
}

filteredStudentList -[hidden]up-> filteredLessonList

Lesson1 <--> Student1

@end
