@startuml
!include style.puml

start
:Get client at index;
if () then ([command contains\nempty appointment])
    if () then ([client has existing\nappointment])
        :Remove existing\nappointment;
    else ([else])
        :Do nothing;
    endif
else ([else])
    if () then ([client has existing\nappointment])
        :Replace existing\nappointment;
    else ([else])
        :Assign new\nappointment;
    endif
endif

stop

@enduml
