@startuml
!include style.puml

Actor User as User USER_COLOR

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":CenterPanel" as CenterPanel UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
end box


User -> MainWindow : "calendar"
activate MainWindow

MainWindow -> Logic : executeCommand("calendar")
activate Logic

Logic --> MainWindow : result
deactivate Logic

MainWindow -> MainWindow : handleCalendar()
activate MainWindow

MainWindow -> CenterPanel : displaySchedulePanel()
activate CenterPanel

CenterPanel --> MainWindow
deactivate CenterPanel

MainWindow --> MainWindow
deactivate MainWindow

MainWindow --> User : calendar view
deactivate MainWindow
@enduml
