@startuml
!include style.puml

Participant ":AddressBookParser" as addressBookParser LOGIC_COLOR_T2
Participant ":ScheduleCommandParser" as scheduleCommandParser LOGIC_COLOR
Participant "<<class>>\nParserUtil" as util LOGIC_COLOR_T3
Participant ":Appointment" as appointment MODEL_COLOR
Participant ":ScheduleCommand" as command LOGIC_COLOR_T4

addressBookParser -[LOGIC_COLOR_T2]> scheduleCommandParser :"1 m/04-Aug-2022 17:00"
activate addressBookParser LOGIC_COLOR_T2
activate scheduleCommandParser LOGIC_COLOR

scheduleCommandParser -[LOGIC_COLOR]> util :parseIndex;
activate util LOGIC_COLOR_T3

util -[LOGIC_COLOR_T3]-> scheduleCommandParser :index
deactivate util

scheduleCommandParser -[LOGIC_COLOR]> util :parseAppointment;
activate util LOGIC_COLOR_T3

create appointment
util -[LOGIC_COLOR_T3]-> appointment: Appointment(trimmedDateTime)
activate appointment MODEL_COLOR

appointment -[MODEL_COLOR]-> util :newAppointment
deactivate appointment

util -[LOGIC_COLOR_T3]-> scheduleCommandParser :newAppointment
deactivate util

create command
scheduleCommandParser -[LOGIC_COLOR]> command :ScheduleCommand(index, newAppointment)
activate command LOGIC_COLOR_T4

command -[LOGIC_COLOR_T4]-> scheduleCommandParser :ScheduleCommand
deactivate command

scheduleCommandParser -[LOGIC_COLOR]-> addressBookParser :ScheduleCommand
deactivate scheduleCommandParser

deactivate addressBookParser

@enduml
