@startuml
!include style.puml
skinparam defaultFontSize 30

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MainParser" as MainParser LOGIC_COLOR
participant ":FriendCommandParser" as FriendCommandParser LOGIC_COLOR
participant ":ScheduleFriendCommandParser" as ScheduleFriendCommandParser LOGIC_COLOR
participant "c:ScheduleFriendCommand" as ScheduleFriendCommand LOGIC_COLOR
end box

[-> LogicManager : execute("friend --schedule draco -p 2 4 1 -f 1")
activate LogicManager

LogicManager -> MainParser : parseCommand("friend --schedule draco -p 2 4 1 -f 1")
activate MainParser

create FriendCommandParser
MainParser -> FriendCommandParser
activate FriendCommandParser

FriendCommandParser --> MainParser
deactivate FriendCommandParser

MainParser -> FriendCommandParser : parse(" --schedule draco -p 2 4 1 -f 1")
activate FriendCommandParser

create ScheduleFriendCommandParser
FriendCommandParser -> ScheduleFriendCommandParser
activate ScheduleFriendCommandParser

ScheduleFriendCommandParser --> FriendCommandParser
deactivate ScheduleFriendCommandParser

FriendCommandParser -> ScheduleFriendCommandParser : parse("--schedule draco -p 2 4 1 -f 1")
activate ScheduleFriendCommandParser

create ScheduleFriendCommand
ScheduleFriendCommandParser -> ScheduleFriendCommand
activate ScheduleFriendCommand

ScheduleFriendCommand --> ScheduleFriendCommandParser : c
deactivate ScheduleFriendCommand

ScheduleFriendCommandParser --> FriendCommandParser : c
deactivate ScheduleFriendCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ScheduleFriendCommandParser -[hidden]-> FriendCommandParser
destroy ScheduleFriendCommandParser

FriendCommandParser --> MainParser : c
deactivate FriendCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FriendCommandParser -[hidden]-> MainParser
destroy FriendCommandParser

MainParser --> LogicManager : c
deactivate MainParser

group ref [execute ScheduleFriendCommand]
LogicManager -[hidden]-> LogicManager
ScheduleFriendCommand -[hidden]-> ScheduleFriendCommand
end

[<--LogicManager
deactivate LogicManager

@enduml
