@startuml
!include style.puml

start
if () then ([command is valid])
  :Identify type of input;
  :Process input arguments into list of words;
	:Create corresponding predicates;
	:Update student list\nwith matched students;
else ([else])
	:Display an error message;
endif

stop

@enduml
