@startuml
!include style.puml

start

:User executes command;
:Identify type of input;

if () then ([input is valid])
  :Process input argument\ninto list of words;
	:Create corresponding predicates;
	:Update student list\nwith matched students;
else ([else])
	:Display an\nerror message;
endif

stop

@enduml
