@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ShowCommandParser" as ShowCommandParser LOGIC_COLOR
participant "showCommand\n:ShowCommand" as ShowCommand LOGIC_COLOR
participant "info\n:Info" as Info LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "studentStatistics\n:StudentStatistics" as StudentStatistics MODEL_COLOR
end box

[-> LogicManager : execute("show \n-n Hong Fai")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(\n"show -n Hong Fai")
activate AddressBookParser

create ShowCommandParser
AddressBookParser -> ShowCommandParser
activate ShowCommandParser

ShowCommandParser --> AddressBookParser
deactivate ShowCommandParser

AddressBookParser -> ShowCommandParser : parse("-n Hong Fai")
activate ShowCommandParser

ShowCommandParser -> ShowCommandParser : parseByPrefixes()
activate ShowCommandParser

create ShowCommand
ShowCommandParser -> ShowCommand : ShowCommand(scoreDescriptor)
activate ShowCommand

ShowCommand --> ShowCommandParser : showCommand
deactivate ShowCommand

ShowCommandParser --> ShowCommandParser : showCommand
deactivate ShowCommandParser

ShowCommandParser --> AddressBookParser : showCommand
deactivate ShowCommandParser

'hidden arrow to position destroy marker
Model -[hidden]->
destroy ShowCommandParser

AddressBookParser --> LogicManager : showCommand
deactivate AddressBookParser

'hidden arrow to position destroy marker
Model -[hidden]->
destroy AddressBookParser

LogicManager -> ShowCommand : execute()
activate ShowCommand

ShowCommand -> ShowCommand : createStudentPredicate()
activate ShowCommand

ShowCommand --> ShowCommand : predicate
deactivate ShowCommand

ShowCommand -> Model : updateFilteredStudentList(predicate)
Model --> ShowCommand : matchedStudent

create Info
ShowCommand -> Info : Info(matchedStudent)
activate Info

Info --> ShowCommand : info
deactivate Info

create StudentStatistics
ShowCommand -> StudentStatistics : StudentStatistics(matchedStudent)
activate StudentStatistics

StudentStatistics --> ShowCommand : studentStatistics
deactivate StudentStatistics

create CommandResult
ShowCommand -> CommandResult
activate CommandResult

CommandResult --> ShowCommand
deactivate CommandResult

ShowCommand --> LogicManager
deactivate ShowCommand

[<--LogicManager
deactivate LogicManager

@enduml
