@startuml
!include style.puml

title: Show performance analysis\nof a group / an assessment

start
if () then ([group / assessment\n  found in database])
	:Update student list with\nstudents in group / cohort;
	:Show summary info of\nstudents in group / cohort;
  :Show performance graph of\nstudents in group / cohort;
else ([else])
	:Display an\nerror message;
endif

stop

@enduml
