@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
}

package "Archive Storage" #F4F6F6{
Interface ArchiveStorage <<Interface>>
Class JsonArchiveStorage
Class JsonSerializableArchive
}

Class JsonAdaptedPerson
Class JsonAdaptedTag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" ArchiveStorage
StorageManager -up-> "1" UserPrefsStorage

Storage -left-|> AddressBookStorage
Storage -left-|> ArchiveStorage
Storage -right-|> UserPrefsStorage

JsonAddressBookStorage .up.|> AddressBookStorage
JsonArchiveStorage .up.|> ArchiveStorage
JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonArchiveStorage ..> JsonSerializableArchive
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonSerializableArchive --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
