@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "CsBook Storage" #F4F6F6{
Interface CsBookStorage <<Interface>>
Class JsonCsBookStorage
Class JsonSerializableCsBook
Class JsonAdaptedStudent
Class JsonAdaptedGroup
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" CsBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> CsBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonCsBookStorage .up.|> CsBookStorage
JsonCsBookStorage ..> JsonSerializableCsBook
JsonSerializableCsBook --> "*" JsonAdaptedStudent
JsonSerializableCsBook --> "*" JsonAdaptedGroup


@enduml
