@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "ProgrammerError Storage" #F4F6F6{
Interface ProgrammerErrorStorage <<Interface>>
Class JsonProgrammerErrorStorage
Class JsonSerializableProgrammerError
Class JsonAdaptedStudent
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ProgrammerErrorStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ProgrammerErrorStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonProgrammerErrorStorage .up.|> ProgrammerErrorStorage
JsonProgrammerErrorStorage ..> JsonSerializableProgrammerError
JsonSerializableProgrammerError --> "*" JsonAdaptedStudent

@enduml
