@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Class Student
Class StudentName
Class Phone
Class ParentName
Class Progress
Class LessonName

Student *--> "1"StudentName
Student *--> "0..2" Phone
Student *--> "1"ParentName
Student *--> "0..10"Progress
Student -right-> "*"LessonName


@enduml
