@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Student
Class ProgressList
Class Progress

Student *--> "1" ProgressList

ProgressList *--> "0..10" Progress
@enduml
