@startuml
!include style.puml
'https://plantuml.com/sequence-diagram

box Main STORAGE_COLOR_T1

participant ":MainApp" as MainApp STORAGE_COLOR
end box

box Logic LOGIC_COLOR_T1

participant ":ModelManager" as ModelManager LOGIC_COLOR
participant ":Summary" as Summary LOGIC_COLOR
participant ":AddressBook" as AddressBook LOGIC_COLOR

end box

box Model MODEL_COLOR_T1

participant "contact:Contact" as Contact MODEL_COLOR
end box



create ModelManager
MainApp -> ModelManager
activate ModelManager


create Summary
ModelManager -> Summary : Summary(addressBook)
activate Summary

Summary -> AddressBook : getContactList()
activate AddressBook

AddressBook --> Summary : contactList
deactivate AddressBook

Summary -> Summary : setNumberOfContacts()
activate Summary

Summary --> Summary
deactivate Summary

Summary -> Summary : setPercentageReviews()
activate Summary

loop addressBookSize
Summary -> Contact : getReview()
activate Contact

Contact --> Summary
deactivate Contact
end
Summary --> Summary
deactivate Summary

Summary -> Summary : setNumberCategory()
activate Summary

loop addressBookSize
Summary -> Contact : getCategoryCode()
activate Contact

Contact --> Summary
deactivate Contact
end

Summary --> Summary
deactivate Summary

Summary --> ModelManager : summary
deactivate Summary


MainApp <-- ModelManager
deactivate ModelManager

@enduml
