@startuml
!include style.puml
box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":TabMenu" as TabMenu UI_COLOR
participant ":TabPane" as TabPane UI_COLOR

activate MainWindow
activate TabMenu
activate TabPane
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ContactsTabParser" as ContactsTabParser LOGIC_COLOR
participant ":SwitchTabContactsCommand" as SwitchTabContactsCommand LOGIC_COLOR
MainWindow -> LogicManager: execute("task")
activate LogicManager


alt #pink User is on Contacts Tab
	LogicManager -> ContactsTabParser: parseCommand("task")
	activate ContactsTabParser
	ContactsTabParser -> SwitchTabContactsCommand
	activate SwitchTabContactsCommand
	SwitchTabContactsCommand --> ContactsTabParser: c
	destroy SwitchTabContactsCommand
	ContactsTabParser --> LogicManager: c
	destroy ContactsTabParser
else User is on Tasks Tab
	ref over LogicManager : Implementation hidden

else User is on Help Tab
	ref over LogicManager : Implementation hidden
end
LogicManager --> MainWindow

alt #lightcyan User switches to Contacts Tab
	ref over MainWindow : Implementation hidden
else User switches to Tasks tab
	MainWindow -> MainWindow: handleSwitchTasksTab()
	activate MainWindow
	MainWindow -> TabMenu: switchTab(1)
	TabMenu -> TabPane: getSelectionModel().select(1)
	TabPane --> TabMenu
	destroy TabPane
	TabMenu --> MainWindow
	destroy TabMenu
	MainWindow -> LogicManager: setTabNumber(1)
	LogicManager --> MainWindow
else User switches to Help Tab
	ref over MainWindow : Implementation hidden
else User chooses to exit
	ref over MainWindow : Implementation hidden
end
	destroy LogicManager
@enduml
