@startuml
skinparam arrowThickness 1.1
skinparam arrowColor #000000
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
show fields

title After TagCommand is executed

object "__:Person__" as normalPerson {
tags
}

object "__:PriorityTag__" as PriorityTag {
tagName = "LowPriority"
}

normalPerson --> PriorityTag

@enduml
