@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Task <<Rectangle>> {
abstract Class Task
Class TaskName
Class Description
Class TaskDate
enum Priority <<Enumeration>>
Class TodoTask
Class EventTask
Class DeadlineTask
}

Task *-up-> "1"TaskName
Task .up.> Priority
Task *-up-> "0..1"Description
Task *-right-> "*"Tag

TodoTask -up-|> Task
EventTask -up-|> Task
DeadlineTask -up-|> Task

TodoTask -[hidden]left- EventTask
EventTask -[hidden]left- DeadlineTask

DeadlineTask *--> "1" TaskDate
EventTask *--> "1" TaskDate

@enduml
