@startuml
'https://plantuml.com/class-diagram

UniqueId "*" <--> "1" Person
UniqueId "*" <--> "1" Task

class UniqueId {
    owner
    id
}

class Person {
    UniqueId id
    updateAssignedTaskIds()
}

class Task {
    UniqueId id
    updateAssignedPersonIds()
}

@enduml
