@startuml
!include style.puml

'mainframe **sd** execute logic of "toggle" user input

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PlannerMdParser" as PlannerMdParser LOGIC_COLOR
participant "t:ToggleCommand" as ToggleCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("toggle")
activate LogicManager

LogicManager -> Model : getState()
activate Model

Model --> LogicManager : state
deactivate Model

LogicManager -> PlannerMdParser : parseCommand("toggle", state)
activate PlannerMdParser

create ToggleCommand
PlannerMdParser -> ToggleCommand
activate ToggleCommand

ToggleCommand --> PlannerMdParser : t
deactivate ToggleCommand

PlannerMdParser --> LogicManager : t
deactivate PlannerMdParser

LogicManager -> ToggleCommand : execute()
activate ToggleCommand

ToggleCommand -> Model : toggleState()
activate Model

Model --> ToggleCommand
deactivate Model

create CommandResult
ToggleCommand -> CommandResult
activate CommandResult

CommandResult --> ToggleCommand :result
deactivate CommandResult

ToggleCommand --> LogicManager : result
deactivate ToggleCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
