@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class StatsDisplay
Class ResultDisplay
Class AnimeListPanel
Class AnimeCard
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" AnimeListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" StatsDisplay

AnimeListPanel -down-> "*" AnimeCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
AnimeListPanel --|> UiPart
AnimeCard --|> UiPart
StatusBarFooter --|> UiPart
StatsDisplay --|> UiPart

AnimeCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

StatsDisplay -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
