@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class UiManager
Class MainWindow
Class WelcomeWindow
Class PersonListPanel
Class PersonCard
Class PersonDetails
Class TabPaneHeader
Class Windows #000000
Class OtherComponents #000000
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
UiManager -right-> "1" WelcomeWindow
MainWindow *-down-> "1" PersonListPanel
MainWindow *-right-> "1" PersonDetails
MainWindow *-left-> Windows
MainWindow *-right-> OtherComponents

PersonListPanel --> "*" PersonCard
PersonListPanel --> "1" PersonDetails
PersonListPanel --> "1" TabPaneHeader

PersonCard ..> Model
UiManager --> Logic
MainWindow --> Logic

Model *--> PersonListPanel

@enduml
