@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class ClientListPanel
Class ClientCard
Class StatusBarFooter
Class SideBar
Class ClientViewPanel
Class MeetingsListPanel
Class NextMeetingCard
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel<<Hidden>> #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic<<Hidden>> #FFFFFF
}

Class HiddenOutside<<Hidden>> #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" ClientListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" SideBar
MainWindow --> "0..1" HelpWindow

ClientListPanel -down-> "*" ClientCard
SideBar -down-> "1" ClientViewPanel
SideBar -down-> "1" MeetingsListPanel

MeetingsListPanel -down-> "*" NextMeetingCard

ClientCard ..> Model
NextMeetingCard .down.> Model
ClientViewPanel .down.> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ClientListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

@enduml
