@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":RhrhParser" as RhrhParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedRhrh" as VersionedRhrh MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> RhrhParser : parseCommand(undo)
activate RhrhParser

create UndoCommand
RhrhParser -> UndoCommand
activate UndoCommand

UndoCommand --> RhrhParser
deactivate UndoCommand

RhrhParser --> LogicManager : u
deactivate RhrhParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoRhrh()
activate Model

Model -> VersionedRhrh : undo()
activate VersionedRhrh

VersionedRhrh -> VersionedRhrh :resetData(ReadOnlyRhrh)
VersionedRhrh --> Model :
deactivate VersionedRhrh

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
