@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":Track2GatherParser" as Track2GatherParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTrack2Gather" as VersionedTrack2Gather MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> Track2GatherParser : parseCommand(undo)
activate Track2GatherParser

create UndoCommand
Track2GatherParser -> UndoCommand
activate UndoCommand

UndoCommand --> Track2GatherParser
deactivate UndoCommand

Track2GatherParser --> LogicManager : u
deactivate Track2GatherParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoTrack2Gather()
activate Model

Model -> VersionedTrack2Gather : undo()
activate VersionedTrack2Gather

VersionedTrack2Gather -> VersionedTrack2Gather :resetData(ReadOnlyTrack2Gather)
VersionedTrack2Gather--> Model :
deactivate VersionedTrack2Gather

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
