@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MrTechRecruiterParser" as MrTechRecruiterParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
participant ":History" as History LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> MrTechRecruiterParser : parseCommand(undo)
activate MrTechRecruiterParser

create UndoCommand
MrTechRecruiterParser -> UndoCommand
activate UndoCommand

UndoCommand --> MrTechRecruiterParser
deactivate UndoCommand

MrTechRecruiterParser --> LogicManager : u
deactivate MrTechRecruiterParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : recoverHistory()
activate Model

Model -> History : recoverHistory()
activate History

History --> Model : m:Memento
deactivate History

Model -> Model :resetData(m)

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
