@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "list"

package States <<rectangle>> {
    class State1 as "__tg0:Track2Gather__"
    class State2 as "__tg1:Track2Gather__"
    class State3 as "__tg2:Track2Gather__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
