@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UnenrollCommandParser" as UnenrollCommandParser LOGIC_COLOR
participant "u:UnenrollCommand" as UnenrollCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "l:Lesson" as Lesson MODEL_COLOR
participant "Alice:Student" as Student MODEL_COLOR
end box

[-> LogicManager : execute("unenroll 2 l/1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("unenroll 2 l/1")
activate AddressBookParser

create UnenrollCommandParser
AddressBookParser -> UnenrollCommandParser
activate UnenrollCommandParser

UnenrollCommandParser --> AddressBookParser
deactivate UnenrollCommandParser

AddressBookParser -> UnenrollCommandParser : parse("2 l/1")
activate UnenrollCommandParser

create UnenrollCommand
UnenrollCommandParser -> UnenrollCommand
activate UnenrollCommand

UnenrollCommand --> UnenrollCommandParser : u
deactivate UnenrollCommand

UnenrollCommandParser --> AddressBookParser : u
deactivate UnenrollCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UnenrollCommandParser -[hidden]-> AddressBookParser
destroy UnenrollCommandParser

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UnenrollCommand : execute()
activate UnenrollCommand

UnenrollCommand -> Lesson : removeStudent(2)
activate Lesson

Lesson -> Student : unenrollFromLesson(Alice)
activate Student

Student -> Lesson
deactivate Student

Lesson --> UnenrollCommand
deactivate Lesson

create CommandResult
UnenrollCommand -> CommandResult
activate CommandResult

CommandResult --> UnenrollCommand
deactivate CommandResult

UnenrollCommand --> LogicManager : result
deactivate UnenrollCommand

[<--LogicManager
deactivate LogicManager
@enduml
