@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":Logic\nManager" as LogicManager LOGIC_COLOR
participant ":Tuitione\nParser" as TuitioneParser LOGIC_COLOR
participant ":UnenrollCommand\nParser" as UnenrollCommandParser LOGIC_COLOR
participant "u:Unenroll\nCommand" as UnenrollCommand LOGIC_COLOR
participant ":Command\nResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "l:Lesson" as Lesson MODEL_COLOR
participant "Alice\n:Student" as Student MODEL_COLOR
end box

[-> LogicManager : execute\n("unenroll 2 l/1")
activate LogicManager

LogicManager -> TuitioneParser : parseCommand\n("unenroll 2 l/1")
activate TuitioneParser

create UnenrollCommandParser
TuitioneParser -> UnenrollCommandParser
activate UnenrollCommandParser

UnenrollCommandParser --> TuitioneParser
deactivate UnenrollCommandParser

TuitioneParser -> UnenrollCommandParser : parse("2 l/1")
activate UnenrollCommandParser

create UnenrollCommand
UnenrollCommandParser -> UnenrollCommand
activate UnenrollCommand

UnenrollCommand --> UnenrollCommandParser : u
deactivate UnenrollCommand

UnenrollCommandParser --> TuitioneParser : u
deactivate UnenrollCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UnenrollCommandParser -[hidden]-> TuitioneParser
destroy UnenrollCommandParser

TuitioneParser --> LogicManager : u
deactivate TuitioneParser

LogicManager -> UnenrollCommand : execute()
activate UnenrollCommand

UnenrollCommand -> Lesson : removeStudent(2)
activate Lesson

Lesson -> Student : unenrollFrom\nLesson(Alice)
activate Student

Student -> Lesson
deactivate Student

Lesson --> UnenrollCommand
deactivate Lesson

create CommandResult
UnenrollCommand -> CommandResult
activate CommandResult

CommandResult --> UnenrollCommand
deactivate CommandResult

UnenrollCommand --> LogicManager : result
deactivate UnenrollCommand

[<--LogicManager
deactivate LogicManager
@enduml
