@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UnfavoriteCommandParser" as UnfavoriteCommandParser LOGIC_COLOR
participant ":UnfavoriteCommand" as UnfavoriteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("unfav 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("unfav 1")
activate AddressBookParser

create UnfavoriteCommandParser
AddressBookParser -> UnfavoriteCommandParser
activate UnfavoriteCommandParser

UnfavoriteCommandParser --> AddressBookParser
deactivate UnfavoriteCommandParser

AddressBookParser -> UnfavoriteCommandParser : parse("1")
activate UnfavoriteCommandParser

create UnfavoriteCommand
UnfavoriteCommandParser -> UnfavoriteCommand
activate UnfavoriteCommand

UnfavoriteCommand --> UnfavoriteCommandParser :
deactivate UnfavoriteCommand

UnfavoriteCommandParser --> AddressBookParser
deactivate UnfavoriteCommandParser

AddressBookParser --> LogicManager :
deactivate AddressBookParser

LogicManager -> UnfavoriteCommand : execute()
activate UnfavoriteCommand

UnfavoriteCommand -> UnfavoriteCommand : execute(model)
activate UnfavoriteCommand
UnfavoriteCommand --> UnfavoriteCommand :
deactivate UnfavoriteCommand

UnfavoriteCommand -> Model : model.unfavouritePerson()
activate Model
Model --> UnfavoriteCommand :
deactivate Model

create CommandResult
UnfavoriteCommand -> CommandResult
activate CommandResult

CommandResult --> UnfavoriteCommand : result
deactivate CommandResult

UnfavoriteCommand --> LogicManager : result
deactivate UnfavoriteCommand

[<--LogicManager

@enduml
