@startuml
start
:User executes Unmark Command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command is valid with valid and
 non-duplicated index/indices])

    if () then ([applicant(s) at all indices
  have been marked])
    :Update specified applicant(s) to be unmarked;

    :GUI Result Display updated with specified
    applicant(s) being unmarked with Not Done;

    else ([else])

    endif

else([else])


endif
stop
@enduml
