@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters command: unpin <index>;
switch()
case ([Contact at specified index exists])
  :CONNECTIONS checks if contact is already pinned;
  if () then ([Contact is pinned])
    : CONNECTIONS unpin contact;
    : CONNECTIONS places contact behind pinned contacts and in front of other unpinned contacts;
    -CONNECTIONS displays contact details
  else ([Contact is not pinned])
    : CONNECTIONS displays message: "Contact is not pinned!";
  endif
case ([No contact at specified index])
  :CONNECTIONS displays error message: "The contact index provided is out of range.";
endswitch


stop

@enduml
