@startuml
!include style.puml
participant ":MainWindow" as MainWindow UI_COLOR
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskTabParser" as TaskTabParser LOGIC_COLOR
participant "command:UpcomingTaskCommand" as UpcomingTaskCommand LOGIC_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
participant "commandResult:CommandResult" as CommandResult LOGIC_COLOR

activate MainWindow UI_COLOR
MainWindow -> LogicManager: execute("upcoming")
activate LogicManager LOGIC_COLOR

LogicManager -> TaskTabParser: parseCommand(...)
activate TaskTabParser LOGIC_COLOR

create UpcomingTaskCommand
TaskTabParser -> UpcomingTaskCommand
activate UpcomingTaskCommand LOGIC_COLOR
UpcomingTaskCommand --> TaskTabParser
deactivate UpcomingTaskCommand

TaskTabParser --> LogicManager: command
deactivate TaskTabParser

LogicManager -> UpcomingTaskCommand: execute(model)
activate UpcomingTaskCommand LOGIC_COLOR

UpcomingTaskCommand -> ModelManager: sortTaskList()
activate ModelManager MODEL_COLOR
ModelManager --> UpcomingTaskCommand
deactivate ModelManager

UpcomingTaskCommand -> ModelManager: updateFilteredTaskList(predicate)
activate ModelManager MODEL_COLOR
ModelManager --> UpcomingTaskCommand
deactivate ModelManager

create CommandResult
UpcomingTaskCommand -> CommandResult
activate CommandResult LOGIC_COLOR
CommandResult --> UpcomingTaskCommand: commandResult
deactivate CommandResult

UpcomingTaskCommand --> LogicManager: commandResult
deactivate UpcomingTaskCommand

LogicManager --> MainWindow: commandResult
deactivate LogicManager

@enduml
