@startuml
start
:User executes AddCommand;

if () is ([Valid Input]) then
:Add contact to existing list of contacts;
:Update GUI to display list of contacts;
else ([Else])
:Show error message;
endif
stop
@enduml
