@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "logic:Logic" as Logic LOGIC_COLOR
participant "addressBookParser:AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "command:TagCommand" as TagCommand LOGIC_COLOR
participant "command:TagCommand" as TagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box


[-> Logic : execute("tag")
activate Logic

Logic -> AddressBookParser : parseCommand("tag")
activate AddressBookParser

create TagCommand
AddressBookParser -> TagCommand
activate TagCommand

TagCommand --> AddressBookParser : command
deactivate TagCommand

AddressBookParser --> Logic : command
deactivate AddressBookParser

AddressBookParser -[hidden]-> Logic
destroy AddressBookParser

Logic -> TagCommand : execute()
activate TagCommand

create CommandResult
TagCommand -> CommandResult
activate CommandResult

CommandResult --> TagCommand : commandResult
deactivate CommandResult

'Hidden arrow to position the destroy marker below the end of the activation bar.
CommandResult -[hidden]-> AddressBookParser
destroy CommandResult

TagCommand --> Logic : commandResult
deactivate TagCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommand -[hidden]-> Logic
destroy TagCommand

[<-- Logic : commandResult
deactivate Logic



@enduml
