@startuml
!include style.puml

skinparam classFontSize 18
skinparam packageFontSize 18
skinparam classStereotypeFontSize 18
skinparam defaultFontSize 18

box Logic LOGIC_COLOR_T1
participant "logic:LogicManager" as LogicManager LOGIC_COLOR
participant "tutorAidParser:TutorAidParser" as TutorAidParser LOGIC_COLOR
participant ":ViewStudentCommand" as ViewStudentCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

box Ui UI_COLOR_T1
participant "ui:UIManager" as UIManager UI_COLOR
end box

[-> LogicManager: execute("view -s 1")
activate LogicManager

LogicManager -> TutorAidParser: parseCommand("view -s 1")
activate TutorAidParser

create ViewStudentCommand
TutorAidParser -> ViewStudentCommand:
activate ViewStudentCommand

TutorAidParser <-- ViewStudentCommand:
deactivate ViewStudentCommand

LogicManager <-- TutorAidParser:
deactivate TutorAidParser

LogicManager -> ViewStudentCommand: execute()
activate ViewStudentCommand

ViewStudentCommand -> Model: viewStudent(student)
activate Model

Model -> ModelManager: viewStudent(student)
activate ModelManager

ModelManager -> UIManager: showViewWindow()
activate UIManager

ModelManager <-- UIManager:
deactivate UIManager

Model <-- ModelManager:
deactivate ModelManager

ViewStudentCommand <-- Model:
deactivate Model

LogicManager <-- ViewStudentCommand: result
deactivate ViewStudentCommand

[<-- LogicManager:
deactivate LogicManager
@enduml
