@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "logic:LogicManager" as LogicManager LOGIC_COLOR
participant "addressBookParser:AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "command:TagCommand" as TagCommand LOGIC_COLOR
participant "command:TagCommand" as TagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("tag")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("tag")
activate AddressBookParser

create TagCommand
AddressBookParser -> TagCommand
activate TagCommand

TagCommand --> AddressBookParser : command
deactivate TagCommand

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> TagCommand : execute()
activate TagCommand

create CommandResult
TagCommand -> CommandResult
activate CommandResult

CommandResult --> TagCommand : commandResult
deactivate CommandResult

'Hidden arrow to position the destroy marker below the end of the activation bar.
CommandResult -[hidden]-> AddressBookParser
destroy CommandResult

TagCommand --> LogicManager : commandResult
deactivate TagCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommand -[hidden]-> AddressBookParser
destroy TagCommand

[<--LogicManager
deactivate LogicManager
@enduml
