@startuml
start
:user inputs visit command;
:Logic executes visit command;
:VisitCommandParser parses the command;

if () then ([Visit date is specified in correct format])
    if() then ([Frequency and occurrence both present])
        if() then ([Both frequency and occurrence are correctly specified])
            :execute VisitCommand;
        else ([else])
            :Throw ParseException;
        endif

    else ([else])
        if() then ([Neither frequency nor occurrence present])
            :execute VisitCommand;
        else ([else])
            :Throw ParseException;
        endif
    endif

else ([else])
    :Throw ParseException;

endif
stop

@enduml
