@startuml
skinparam wrapWidth 130
skinparam defaultTextAlignment center

start
:User inputs visit command;
:Logic executes visit command;
:VisitCommandParser parses the command;

if () then ([Visit date is in correct format])
    if() then ([Frequency and occurrence
    both present])
        if() then ([Both frequency
  and occurrence
  are correctly specified])
            :Execute VisitCommand;
        else ([else])
            :Throw ParseException;
        endif

    else ([else])
        if() then ([Neither frequency
 nor occurrence present])
            :Execute VisitCommand;
        else ([else])
            :Throw ParseException;
        endif
    endif

else ([else])
    :Throw ParseException;

endif
stop

@enduml
