@startuml
start
:User executes command;
:Command attempts to
fetch position to visualize;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid position])
    :Check if position has applicants;
    if () then ([applicants found])
        :Generate pie chart of position;
        :Display pie chart to user;
    else ([else])
        :'No applicants'
        error message shown;
    endif

else ([else])
    :'Invalid position'
    error message shown;
endif
stop
@enduml
