@startuml
!include ../style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic LOGIC_COLOR
logic -> abp ++ LOGIC_COLOR: parseCommand(commandText)
create ecp
abp -> ecp
abp -> ecp ++ LOGIC_COLOR: parse(arguments)
create ec
ecp -> ec ++ LOGIC_COLOR: index, editClientDescriptor
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command

@enduml
