@startuml
!include ../style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AcademyDirectoryParser" as adp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> adp ++: parseCommand(commandText)
create ecp
adp -> ecp
adp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editStudentDescriptor
ec --> ecp --
ecp --> adp --: command
adp --> logic --: command

@enduml
