@startuml
!include ../style.puml

box "Logic" #FFFFFF
Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":SearchCommandParser" as fcp LOGIC_COLOR
Participant "command:SearchCommand" as fc LOGIC_COLOR
Participant "result:CommandResult" as cr LOGIC_COLOR
Participant "predicate:ClientContainsKeywordPredicate" as pckp LOGIC_COLOR
end box
box "Model" #FFFFFF
Participant "model:Model" as model MODEL_COLOR
end box

skinparam sequenceBoxBorderColor #black
[-> logic : execute
activate logic LOGIC_COLOR
logic -> abp ++ LOGIC_COLOR: parseCommand(commandText)
create fcp
abp -> fcp
abp -> fcp ++ LOGIC_COLOR: parse(arguments)
create pckp
fcp -> pckp ++ LOGIC_COLOR: argMultiMap
pckp --> fcp --:
create fc
fcp -> fc ++ LOGIC_COLOR: predicate
fc --> fcp --: command
fcp --> abp --: command
abp --> logic --: command
logic -> fc ++ LOGIC_COLOR: execute(model)
fc -> model ++ MODEL_COLOR: updateFilteredClientList(predicate)
loop all client
    model -> pckp ++ LOGIC_COLOR: test(client)
    pckp --> model --
end
model --> fc --:
create cr
fc -> cr ++ LOGIC_COLOR:
cr --> fc --:
fc --> logic --: result
logic -->[ --: result



@enduml
