@startuml
!include ../style.puml

box "Logic" #FFFFFF
Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":SortCommandParser" as scp LOGIC_COLOR
Participant "command:SortCommand" as sc LOGIC_COLOR
Participant "result:CommandResult" as cr LOGIC_COLOR
Participant "sortDirection:SortDirection" as sd LOGIC_COLOR
Participant "sorter:SortByAttribute" as sba LOGIC_COLOR
end box
box "Model" #FFFFFF
Participant "model:Model" as model MODEL_COLOR
end box

skinparam sequenceBoxBorderColor #black

[-> logic : execute
activate logic LOGIC_COLOR
logic -> abp ++ LOGIC_COLOR: parseCommand(commandText)

create scp
abp -> scp
abp -> scp ++ LOGIC_COLOR: parse(arguments)
scp -> scp ++ LOGIC_COLOR_T1: getPrefix(argMultimap, ALL_PREFIXES)
scp -> scp -- LOGIC_COLOR: prefix
create sd LOGIC_COLOR
scp -> sd ++ LOGIC_COLOR: sortDirection
sd --> scp --:
create sba
scp -> sba ++ LOGIC_COLOR: prefix, sortDirection
sba --> scp --:
create sc
scp -> sc ++ LOGIC_COLOR: sorter
sc --> scp --: command
scp --> abp --: command
abp --> logic --: command
logic -> sc ++ LOGIC_COLOR: execute(model)
sc -> model ++ MODEL_COLOR: sortFilteredClientList(predicate)
loop all client
    model -> sba ++ LOGIC_COLOR: compare(client1, client2)
    sba --> model --
end
model --> sc --:
create cr
sc -> cr ++ LOGIC_COLOR:
cr --> sc --:
sc --> logic --: result
logic -->[ --: result



@enduml
