@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TdoneCommand" as TdoneCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
participant ":Task" as Task MODEL_COLOR
end box

LogicManager -> TdoneCommand : execute(:Model)
activate TdoneCommand

TdoneCommand -> Model : getFilteredTaskList()
activate Model

Model --> TdoneCommand : filteredTaskList
deactivate Model

loop for each task to be marked as completed

create Task
TdoneCommand -> Task
activate Task

Task --> TdoneCommand : completedTask
deactivate Task

TdoneCommand -> Model : setTask(targetTask, completedTask)
activate Model

Model --> TdoneCommand
deactivate Model
end loop

create CommandResult
TdoneCommand -> CommandResult
activate CommandResult

CommandResult --> TdoneCommand
deactivate CommandResult

TdoneCommand --> LogicManager : result
deactivate TdoneCommand

TdoneCommand -[hidden]-> LogicManager
destroy TdoneCommand

[<--LogicManager
deactivate LogicManager
@enduml
