@startuml
!include ../style.puml
mainframe **sd** TaddCommand Execution

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaddCommand" as TaddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

LogicManager -> TaddCommand : execute(:Model)
activate TaddCommand

TaddCommand -> Model : getFilteredMemberList()
activate Model

Model --> TaddCommand : filteredMemberList
deactivate Model

loop for each member to be assigned the task
TaddCommand -> Model : addTask(targetMember, taskToAdd)
activate Model

Model --> TaddCommand
deactivate Model
end loop

create CommandResult
TaddCommand -> CommandResult
activate CommandResult

CommandResult --> TaddCommand
deactivate CommandResult

TaddCommand --> LogicManager : result
deactivate TaddCommand

TaddCommand -[hidden]-> LogicManager
destroy TaddCommand

[<--LogicManager
deactivate LogicManager
@enduml
