@startuml
!include ../../../style.puml

Participant ":SortCommand" as sc LOGIC_COLOR
Participant "<<class>>\nName" as name LOGIC_COLOR
Participant "<<class>>\nParticipation" as part LOGIC_COLOR
Participant "<<class>>\nAssessment" as assess LOGIC_COLOR

activate sc
sc -> sc ++ : getComparator

alt NAME
sc -> name ++ : getComparator(isAscendingOrder)
name --> sc -- : comparator

else PARTICIPATION
sc -> part ++ : getComparator(isAscendingOrder)
part --> sc -- : comparator

else AVERAGE
sc -> assess ++ : getAverageComparator(isAscendingOrder)
assess --> sc -- : comparator

else else
sc -> assess ++ : getIndividualComparator(isAscendingOrder, attribute)
assess --> sc -- : comparator

end

sc --> sc -- : comparator

@enduml
