@startuml
!include ../../../style.puml

box Logic LOGIC_COLOR_T1
participant ":HistoryCommand" as historyCommand LOGIC_COLOR
participant ":CommandResult" as commandResult LOGIC_COLOR
end box

box VersionedModel MODEL_COLOR_T1
participant "model:VersionedModel" as versionedModel MODEL_COLOR
participant "main:Commit" as mainCommit MODEL_COLOR
participant "old:Commit" as oldCommit MODEL_COLOR
participant "lca:Commit" as lcaCommit MODEL_COLOR
end box

-> historyCommand ++ : execute(model)
historyCommand -> versionedModel ++ : fetchCommitByLabel("MAIN")
versionedModel --> historyCommand -- : mainCommit
historyCommand -> versionedModel ++ : fetchCommitByLabel("OLD")
versionedModel --> historyCommand -- : oldCommit

historyCommand -> mainCommit ++ : findLca(oldCommit)
mainCommit --> historyCommand -- : lca
create lcaCommit

historyCommand -> lcaCommit ++ : getHistory()
lcaCommit --> historyCommand --

historyCommand -> mainCommit ++ : getHistory(lca)
mainCommit --> historyCommand --

historyCommand -> oldCommit ++ : getHistory(lca)
oldCommit --> historyCommand --

historyCommand -> historyCommand ++-- : getPresentableHistory()
historyCommand -> versionedModel : setAdditionalViewModel(presentableHistory)
create commandResult
historyCommand -> commandResult ++ : new CommandResult(MESSAGE_SUCCESS)
commandResult --> historyCommand -- : commandResult
<-- historyCommand -- : commandResult
@enduml
