# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/AY2122S1-CS2103T-F13-3/tp" }

gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'wdm', '~> 0.1.0' if Gem.win_platform?

gem "webrick", "~> 1.7"
