@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TeachingAssistantBuddyParser" as TeachingAssistantBuddyParser LOGIC_COLOR
participant ":FindStudentCommandParser" as FindStudentCommandParser LOGIC_COLOR
participant "d:FindStudentCommand" as FindStudentCommand LOGIC_COLOR
end box

[-> LogicManager : execute("find m/CS2103 i/A1234567A")
activate LogicManager

LogicManager -> TeachingAssistantBuddyParser : parseCommand("find m/CS2103 i/A1234567A")
activate TeachingAssistantBuddyParser

create FindStudentCommandParser
TeachingAssistantBuddyParser -> FindStudentCommandParser
activate FindStudentCommandParser
FindStudentCommandParser --> TeachingAssistantBuddyParser
deactivate FindStudentCommandParser

TeachingAssistantBuddyParser -> FindStudentCommandParser : parse("m/CS2103 i/A1234567A")
activate FindStudentCommandParser

create FindStudentCommand
FindStudentCommandParser -> FindStudentCommand
activate FindStudentCommand

FindStudentCommand --> FindStudentCommandParser : d
deactivate FindStudentCommand

FindStudentCommandParser --> TeachingAssistantBuddyParser : d
deactivate FindStudentCommandParser

TeachingAssistantBuddyParser --> LogicManager : d
deactivate TeachingAssistantBuddyParser



[<--LogicManager
deactivate LogicManager
@enduml
