@startuml
!include ../../../style.puml
Participant ":GetCommand" as rc LOGIC_COLOR
Participant ":Model" as mm LOGIC_COLOR
Participant ":CommandResult" as result LOGIC_COLOR

-> rc ++ :execute
loop for all InformationWantedFilter
    rc -> rc ++ :executeFilter
    rc -> mm ++  :getFilteredStudentListView(InformationWantedFilter)
    mm --> rc -- : FilteredList
    deactivate
end
rc -> result ++ :CommandResult
return
return CommandResult
@enduml
