name: Repo Wide Checks

on:
  push:
    branches:
      - master
      - 'dev/**'
    paths-ignore:
      - 'src/**'
      - 'gradle/**'
      - 'config/**'
      - '.github/**'
      - 'build.gradle'
  pull_request:
    branches:
      - master
      - 'dev/**'
    paths-ignore:
      - 'src/**'
      - 'gradle/**'
      - 'config/**'
      - '.github/**'
      - 'build.gradle'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Run repository-wide tests
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/.github
        run: ./run-checks.sh
