name: Trim trailing whitespaces in Markdown Files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: ZSH command - trim whitespace
        run: find **/*.md -not \( -name .svn -prune -o -name .git -prune \) -type f -print0 | xargs -0 perl -pi -e 's/ +$//'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Let the markdown elf take a look.
          committer: Github <noreply@github.com>
          author: Github <noreply@github.com>
          signoff: false
          branch: trim-white-space
          branch-suffix: timestamp
          delete-branch: true
          title: 'Trim trailing whitespaces'
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
