@startuml
!include ../../../style.puml

Participant ":ParticipationCommand" as pc LOGIC_COLOR
Participant ":Student" as ste LOGIC_COLOR
Participant ":Attendance" as att LOGIC_COLOR
Participant ":boolean[]" as bla LOGIC_COLOR
Participant ":Attendance" as natt LOGIC_COLOR

activate pc
opt  participationUpdate > 0

loop for each Index in indexArrayList
pc -> ste ++ : getAttendance
ste --> pc -- : attendance

pc -> att ++ : getAttendanceArray
att --> pc -- : newAttArr

pc -> bla ++ : newAttArr[sessionCount - 1] = true
bla --> pc --

create natt
pc -> natt ++ : Attendance(sessionCount)
natt --> pc -- : newAttendance

pc -> natt ++ : setAttendance(newAttArr)
natt --> pc --

pc -> ste ++ : setAttendance(newAttendance)
ste --> pc --
end
end
@enduml
